// #10476: a user method whose NAME matches a Date / Number / Array / String
// built-in must run on a receiver that is not that built-in. Pre-fix such a
// call was lowered to the built-in by name alone (NaN, "[object Object]",
// "Invalid time value", or a compile error for a zero-argument
// `endsWith`/`includes`/`startsWith`). No class here declares these names, so
// an unproven receiver takes the compiler's runtime receiver-kind check: every
// name is defined on a function-constructor prototype, a replaced prototype
// object, an object literal and an Object.create() prototype, and called
// directly, via `this` and via `any`, with real Date / number / array / string
// values as controls at the same call sites.
// Generated by a one-off script: one call site per (form, name, arity).

const cmp = (a: number, b: number) => b - a;
const add = (acc: number, v: number) => acc + v;
const dup = (v: number) => [v, v];

function tag(form: string, name: string, args: any[]): string {
  return form + "." + name + "/" + args.length;
}

function show(v: any): string {
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return "[" + v.join(",") + "]";
  return v === null ? "null" : typeof v;
}

// Error messages for a missing method differ between engines; the name is
// what matters here.
function attempt(f: () => any): string {
  try {
    return show(f());
  } catch (e) {
    return "THREW " + (e as Error).name;
  }
}

function attemptMessage(f: () => any): string {
  try {
    return show(f());
  } catch (e) {
    return "THREW " + String(e);
  }
}

function row(label: string, ...fs: Array<() => any>): void {
  console.log(label, fs.map(attempt).join(" "));
}

function viaAny(x: any, id: number): any {
  switch (id) {
    case 0: return x.getDate();
    case 1: return x.getDay();
    case 2: return x.getFullYear();
    case 3: return x.getHours();
    case 4: return x.getMilliseconds();
    case 5: return x.getMinutes();
    case 6: return x.getMonth();
    case 7: return x.getSeconds();
    case 8: return x.getTime();
    case 9: return x.getTimezoneOffset();
    case 10: return x.getUTCDate();
    case 11: return x.getUTCDay();
    case 12: return x.getUTCFullYear();
    case 13: return x.getUTCHours();
    case 14: return x.getUTCMilliseconds();
    case 15: return x.getUTCMinutes();
    case 16: return x.getUTCMonth();
    case 17: return x.getUTCSeconds();
    case 18: return x.setDate(1);
    case 19: return x.setFullYear(1);
    case 20: return x.setHours(1);
    case 21: return x.setMilliseconds(1);
    case 22: return x.setMinutes(1);
    case 23: return x.setMonth(1);
    case 24: return x.setSeconds(1);
    case 25: return x.setTime(1);
    case 26: return x.setUTCDate(1);
    case 27: return x.setUTCFullYear(1);
    case 28: return x.setUTCHours(1);
    case 29: return x.setUTCMilliseconds(1);
    case 30: return x.setUTCMinutes(1);
    case 31: return x.setUTCMonth(1);
    case 32: return x.setUTCSeconds(1);
    case 33: return x.toISOString();
    case 34: return x.toDateString();
    case 35: return x.toTimeString();
    case 36: return x.toUTCString();
    case 37: return x.toGMTString();
    case 38: return x.toLocaleString();
    case 39: return x.toLocaleDateString();
    case 40: return x.toLocaleTimeString();
    case 41: return x.toFixed(2);
    case 42: return x.toPrecision(2);
    case 43: return x.toExponential(2);
    case 44: return x.toFixed();
    case 45: return x.toSorted();
    case 46: return x.toSorted(cmp);
    case 47: return x.toReversed();
    case 48: return x.reduceRight(add);
    case 49: return x.flat();
    case 50: return x.flatMap(dup);
    case 51: return x.toSpliced(1);
    case 52: return x.toSpliced(0, 1);
    case 53: return x.copyWithin(0, 1);
    case 54: return x.endsWith();
    case 55: return x.includes();
    case 56: return x.startsWith();
    case 57: return x.endsWith('c');
    case 58: return x.includes('b');
    case 59: return x.startsWith('a');
  }
}

function F(this: any) { this.v = 1; }
F.prototype.getDate = function (...a: any[]) { return tag("F", "getDate", a); };
F.prototype.getDay = function (...a: any[]) { return tag("F", "getDay", a); };
F.prototype.getFullYear = function (...a: any[]) { return tag("F", "getFullYear", a); };
F.prototype.getHours = function (...a: any[]) { return tag("F", "getHours", a); };
F.prototype.getMilliseconds = function (...a: any[]) { return tag("F", "getMilliseconds", a); };
F.prototype.getMinutes = function (...a: any[]) { return tag("F", "getMinutes", a); };
F.prototype.getMonth = function (...a: any[]) { return tag("F", "getMonth", a); };
F.prototype.getSeconds = function (...a: any[]) { return tag("F", "getSeconds", a); };
F.prototype.getTime = function (...a: any[]) { return tag("F", "getTime", a); };
F.prototype.getTimezoneOffset = function (...a: any[]) { return tag("F", "getTimezoneOffset", a); };
F.prototype.getUTCDate = function (...a: any[]) { return tag("F", "getUTCDate", a); };
F.prototype.getUTCDay = function (...a: any[]) { return tag("F", "getUTCDay", a); };
F.prototype.getUTCFullYear = function (...a: any[]) { return tag("F", "getUTCFullYear", a); };
F.prototype.getUTCHours = function (...a: any[]) { return tag("F", "getUTCHours", a); };
F.prototype.getUTCMilliseconds = function (...a: any[]) { return tag("F", "getUTCMilliseconds", a); };
F.prototype.getUTCMinutes = function (...a: any[]) { return tag("F", "getUTCMinutes", a); };
F.prototype.getUTCMonth = function (...a: any[]) { return tag("F", "getUTCMonth", a); };
F.prototype.getUTCSeconds = function (...a: any[]) { return tag("F", "getUTCSeconds", a); };
F.prototype.setDate = function (...a: any[]) { return tag("F", "setDate", a); };
F.prototype.setFullYear = function (...a: any[]) { return tag("F", "setFullYear", a); };
F.prototype.setHours = function (...a: any[]) { return tag("F", "setHours", a); };
F.prototype.setMilliseconds = function (...a: any[]) { return tag("F", "setMilliseconds", a); };
F.prototype.setMinutes = function (...a: any[]) { return tag("F", "setMinutes", a); };
F.prototype.setMonth = function (...a: any[]) { return tag("F", "setMonth", a); };
F.prototype.setSeconds = function (...a: any[]) { return tag("F", "setSeconds", a); };
F.prototype.setTime = function (...a: any[]) { return tag("F", "setTime", a); };
F.prototype.setUTCDate = function (...a: any[]) { return tag("F", "setUTCDate", a); };
F.prototype.setUTCFullYear = function (...a: any[]) { return tag("F", "setUTCFullYear", a); };
F.prototype.setUTCHours = function (...a: any[]) { return tag("F", "setUTCHours", a); };
F.prototype.setUTCMilliseconds = function (...a: any[]) { return tag("F", "setUTCMilliseconds", a); };
F.prototype.setUTCMinutes = function (...a: any[]) { return tag("F", "setUTCMinutes", a); };
F.prototype.setUTCMonth = function (...a: any[]) { return tag("F", "setUTCMonth", a); };
F.prototype.setUTCSeconds = function (...a: any[]) { return tag("F", "setUTCSeconds", a); };
F.prototype.toISOString = function (...a: any[]) { return tag("F", "toISOString", a); };
F.prototype.toDateString = function (...a: any[]) { return tag("F", "toDateString", a); };
F.prototype.toTimeString = function (...a: any[]) { return tag("F", "toTimeString", a); };
F.prototype.toUTCString = function (...a: any[]) { return tag("F", "toUTCString", a); };
F.prototype.toGMTString = function (...a: any[]) { return tag("F", "toGMTString", a); };
F.prototype.toLocaleString = function (...a: any[]) { return tag("F", "toLocaleString", a); };
F.prototype.toLocaleDateString = function (...a: any[]) { return tag("F", "toLocaleDateString", a); };
F.prototype.toLocaleTimeString = function (...a: any[]) { return tag("F", "toLocaleTimeString", a); };
F.prototype.toFixed = function (...a: any[]) { return tag("F", "toFixed", a); };
F.prototype.toPrecision = function (...a: any[]) { return tag("F", "toPrecision", a); };
F.prototype.toExponential = function (...a: any[]) { return tag("F", "toExponential", a); };
F.prototype.toSorted = function (...a: any[]) { return tag("F", "toSorted", a); };
F.prototype.toReversed = function (...a: any[]) { return tag("F", "toReversed", a); };
F.prototype.reduceRight = function (...a: any[]) { return tag("F", "reduceRight", a); };
F.prototype.flat = function (...a: any[]) { return tag("F", "flat", a); };
F.prototype.flatMap = function (...a: any[]) { return tag("F", "flatMap", a); };
F.prototype.toSpliced = function (...a: any[]) { return tag("F", "toSpliced", a); };
F.prototype.copyWithin = function (...a: any[]) { return tag("F", "copyWithin", a); };
F.prototype.endsWith = function (...a: any[]) { return tag("F", "endsWith", a); };
F.prototype.includes = function (...a: any[]) { return tag("F", "includes", a); };
F.prototype.startsWith = function (...a: any[]) { return tag("F", "startsWith", a); };
F.prototype.viaThis = function (this: any, id: number): any {
  switch (id) {
    case 0: return this.getDate();
    case 1: return this.getDay();
    case 2: return this.getFullYear();
    case 3: return this.getHours();
    case 4: return this.getMilliseconds();
    case 5: return this.getMinutes();
    case 6: return this.getMonth();
    case 7: return this.getSeconds();
    case 8: return this.getTime();
    case 9: return this.getTimezoneOffset();
    case 10: return this.getUTCDate();
    case 11: return this.getUTCDay();
    case 12: return this.getUTCFullYear();
    case 13: return this.getUTCHours();
    case 14: return this.getUTCMilliseconds();
    case 15: return this.getUTCMinutes();
    case 16: return this.getUTCMonth();
    case 17: return this.getUTCSeconds();
    case 18: return this.setDate(1);
    case 19: return this.setFullYear(1);
    case 20: return this.setHours(1);
    case 21: return this.setMilliseconds(1);
    case 22: return this.setMinutes(1);
    case 23: return this.setMonth(1);
    case 24: return this.setSeconds(1);
    case 25: return this.setTime(1);
    case 26: return this.setUTCDate(1);
    case 27: return this.setUTCFullYear(1);
    case 28: return this.setUTCHours(1);
    case 29: return this.setUTCMilliseconds(1);
    case 30: return this.setUTCMinutes(1);
    case 31: return this.setUTCMonth(1);
    case 32: return this.setUTCSeconds(1);
    case 33: return this.toISOString();
    case 34: return this.toDateString();
    case 35: return this.toTimeString();
    case 36: return this.toUTCString();
    case 37: return this.toGMTString();
    case 38: return this.toLocaleString();
    case 39: return this.toLocaleDateString();
    case 40: return this.toLocaleTimeString();
    case 41: return this.toFixed(2);
    case 42: return this.toPrecision(2);
    case 43: return this.toExponential(2);
    case 44: return this.toFixed();
    case 45: return this.toSorted();
    case 46: return this.toSorted(cmp);
    case 47: return this.toReversed();
    case 48: return this.reduceRight(add);
    case 49: return this.flat();
    case 50: return this.flatMap(dup);
    case 51: return this.toSpliced(1);
    case 52: return this.toSpliced(0, 1);
    case 53: return this.copyWithin(0, 1);
    case 54: return this.endsWith();
    case 55: return this.includes();
    case 56: return this.startsWith();
    case 57: return this.endsWith('c');
    case 58: return this.includes('b');
    case 59: return this.startsWith('a');
  }
};

function G(this: any) { this.v = 2; }
G.prototype = {
  getDate: function (...a: any[]) { return tag("G", "getDate", a); },
  getDay: function (...a: any[]) { return tag("G", "getDay", a); },
  getFullYear: function (...a: any[]) { return tag("G", "getFullYear", a); },
  getHours: function (...a: any[]) { return tag("G", "getHours", a); },
  getMilliseconds: function (...a: any[]) { return tag("G", "getMilliseconds", a); },
  getMinutes: function (...a: any[]) { return tag("G", "getMinutes", a); },
  getMonth: function (...a: any[]) { return tag("G", "getMonth", a); },
  getSeconds: function (...a: any[]) { return tag("G", "getSeconds", a); },
  getTime: function (...a: any[]) { return tag("G", "getTime", a); },
  getTimezoneOffset: function (...a: any[]) { return tag("G", "getTimezoneOffset", a); },
  getUTCDate: function (...a: any[]) { return tag("G", "getUTCDate", a); },
  getUTCDay: function (...a: any[]) { return tag("G", "getUTCDay", a); },
  getUTCFullYear: function (...a: any[]) { return tag("G", "getUTCFullYear", a); },
  getUTCHours: function (...a: any[]) { return tag("G", "getUTCHours", a); },
  getUTCMilliseconds: function (...a: any[]) { return tag("G", "getUTCMilliseconds", a); },
  getUTCMinutes: function (...a: any[]) { return tag("G", "getUTCMinutes", a); },
  getUTCMonth: function (...a: any[]) { return tag("G", "getUTCMonth", a); },
  getUTCSeconds: function (...a: any[]) { return tag("G", "getUTCSeconds", a); },
  setDate: function (...a: any[]) { return tag("G", "setDate", a); },
  setFullYear: function (...a: any[]) { return tag("G", "setFullYear", a); },
  setHours: function (...a: any[]) { return tag("G", "setHours", a); },
  setMilliseconds: function (...a: any[]) { return tag("G", "setMilliseconds", a); },
  setMinutes: function (...a: any[]) { return tag("G", "setMinutes", a); },
  setMonth: function (...a: any[]) { return tag("G", "setMonth", a); },
  setSeconds: function (...a: any[]) { return tag("G", "setSeconds", a); },
  setTime: function (...a: any[]) { return tag("G", "setTime", a); },
  setUTCDate: function (...a: any[]) { return tag("G", "setUTCDate", a); },
  setUTCFullYear: function (...a: any[]) { return tag("G", "setUTCFullYear", a); },
  setUTCHours: function (...a: any[]) { return tag("G", "setUTCHours", a); },
  setUTCMilliseconds: function (...a: any[]) { return tag("G", "setUTCMilliseconds", a); },
  setUTCMinutes: function (...a: any[]) { return tag("G", "setUTCMinutes", a); },
  setUTCMonth: function (...a: any[]) { return tag("G", "setUTCMonth", a); },
  setUTCSeconds: function (...a: any[]) { return tag("G", "setUTCSeconds", a); },
  toISOString: function (...a: any[]) { return tag("G", "toISOString", a); },
  toDateString: function (...a: any[]) { return tag("G", "toDateString", a); },
  toTimeString: function (...a: any[]) { return tag("G", "toTimeString", a); },
  toUTCString: function (...a: any[]) { return tag("G", "toUTCString", a); },
  toGMTString: function (...a: any[]) { return tag("G", "toGMTString", a); },
  toLocaleString: function (...a: any[]) { return tag("G", "toLocaleString", a); },
  toLocaleDateString: function (...a: any[]) { return tag("G", "toLocaleDateString", a); },
  toLocaleTimeString: function (...a: any[]) { return tag("G", "toLocaleTimeString", a); },
  toFixed: function (...a: any[]) { return tag("G", "toFixed", a); },
  toPrecision: function (...a: any[]) { return tag("G", "toPrecision", a); },
  toExponential: function (...a: any[]) { return tag("G", "toExponential", a); },
  toSorted: function (...a: any[]) { return tag("G", "toSorted", a); },
  toReversed: function (...a: any[]) { return tag("G", "toReversed", a); },
  reduceRight: function (...a: any[]) { return tag("G", "reduceRight", a); },
  flat: function (...a: any[]) { return tag("G", "flat", a); },
  flatMap: function (...a: any[]) { return tag("G", "flatMap", a); },
  toSpliced: function (...a: any[]) { return tag("G", "toSpliced", a); },
  copyWithin: function (...a: any[]) { return tag("G", "copyWithin", a); },
  endsWith: function (...a: any[]) { return tag("G", "endsWith", a); },
  includes: function (...a: any[]) { return tag("G", "includes", a); },
  startsWith: function (...a: any[]) { return tag("G", "startsWith", a); },
};

const lit = {
  v: 3,
  getDate(...a: any[]): any { return tag("lit", "getDate", a); },
  getDay(...a: any[]): any { return tag("lit", "getDay", a); },
  getFullYear(...a: any[]): any { return tag("lit", "getFullYear", a); },
  getHours(...a: any[]): any { return tag("lit", "getHours", a); },
  getMilliseconds(...a: any[]): any { return tag("lit", "getMilliseconds", a); },
  getMinutes(...a: any[]): any { return tag("lit", "getMinutes", a); },
  getMonth(...a: any[]): any { return tag("lit", "getMonth", a); },
  getSeconds(...a: any[]): any { return tag("lit", "getSeconds", a); },
  getTime(...a: any[]): any { return tag("lit", "getTime", a); },
  getTimezoneOffset(...a: any[]): any { return tag("lit", "getTimezoneOffset", a); },
  getUTCDate(...a: any[]): any { return tag("lit", "getUTCDate", a); },
  getUTCDay(...a: any[]): any { return tag("lit", "getUTCDay", a); },
  getUTCFullYear(...a: any[]): any { return tag("lit", "getUTCFullYear", a); },
  getUTCHours(...a: any[]): any { return tag("lit", "getUTCHours", a); },
  getUTCMilliseconds(...a: any[]): any { return tag("lit", "getUTCMilliseconds", a); },
  getUTCMinutes(...a: any[]): any { return tag("lit", "getUTCMinutes", a); },
  getUTCMonth(...a: any[]): any { return tag("lit", "getUTCMonth", a); },
  getUTCSeconds(...a: any[]): any { return tag("lit", "getUTCSeconds", a); },
  setDate(...a: any[]): any { return tag("lit", "setDate", a); },
  setFullYear(...a: any[]): any { return tag("lit", "setFullYear", a); },
  setHours(...a: any[]): any { return tag("lit", "setHours", a); },
  setMilliseconds(...a: any[]): any { return tag("lit", "setMilliseconds", a); },
  setMinutes(...a: any[]): any { return tag("lit", "setMinutes", a); },
  setMonth(...a: any[]): any { return tag("lit", "setMonth", a); },
  setSeconds(...a: any[]): any { return tag("lit", "setSeconds", a); },
  setTime(...a: any[]): any { return tag("lit", "setTime", a); },
  setUTCDate(...a: any[]): any { return tag("lit", "setUTCDate", a); },
  setUTCFullYear(...a: any[]): any { return tag("lit", "setUTCFullYear", a); },
  setUTCHours(...a: any[]): any { return tag("lit", "setUTCHours", a); },
  setUTCMilliseconds(...a: any[]): any { return tag("lit", "setUTCMilliseconds", a); },
  setUTCMinutes(...a: any[]): any { return tag("lit", "setUTCMinutes", a); },
  setUTCMonth(...a: any[]): any { return tag("lit", "setUTCMonth", a); },
  setUTCSeconds(...a: any[]): any { return tag("lit", "setUTCSeconds", a); },
  toISOString(...a: any[]): any { return tag("lit", "toISOString", a); },
  toDateString(...a: any[]): any { return tag("lit", "toDateString", a); },
  toTimeString(...a: any[]): any { return tag("lit", "toTimeString", a); },
  toUTCString(...a: any[]): any { return tag("lit", "toUTCString", a); },
  toGMTString(...a: any[]): any { return tag("lit", "toGMTString", a); },
  toLocaleString(...a: any[]): any { return tag("lit", "toLocaleString", a); },
  toLocaleDateString(...a: any[]): any { return tag("lit", "toLocaleDateString", a); },
  toLocaleTimeString(...a: any[]): any { return tag("lit", "toLocaleTimeString", a); },
  toFixed(...a: any[]): any { return tag("lit", "toFixed", a); },
  toPrecision(...a: any[]): any { return tag("lit", "toPrecision", a); },
  toExponential(...a: any[]): any { return tag("lit", "toExponential", a); },
  toSorted(...a: any[]): any { return tag("lit", "toSorted", a); },
  toReversed(...a: any[]): any { return tag("lit", "toReversed", a); },
  reduceRight(...a: any[]): any { return tag("lit", "reduceRight", a); },
  flat(...a: any[]): any { return tag("lit", "flat", a); },
  flatMap(...a: any[]): any { return tag("lit", "flatMap", a); },
  toSpliced(...a: any[]): any { return tag("lit", "toSpliced", a); },
  copyWithin(...a: any[]): any { return tag("lit", "copyWithin", a); },
  endsWith(...a: any[]): any { return tag("lit", "endsWith", a); },
  includes(...a: any[]): any { return tag("lit", "includes", a); },
  startsWith(...a: any[]): any { return tag("lit", "startsWith", a); },
};

const protoLit: any = {};
protoLit.getDate = function (...a: any[]) { return tag("oc", "getDate", a); };
protoLit.getDay = function (...a: any[]) { return tag("oc", "getDay", a); };
protoLit.getFullYear = function (...a: any[]) { return tag("oc", "getFullYear", a); };
protoLit.getHours = function (...a: any[]) { return tag("oc", "getHours", a); };
protoLit.getMilliseconds = function (...a: any[]) { return tag("oc", "getMilliseconds", a); };
protoLit.getMinutes = function (...a: any[]) { return tag("oc", "getMinutes", a); };
protoLit.getMonth = function (...a: any[]) { return tag("oc", "getMonth", a); };
protoLit.getSeconds = function (...a: any[]) { return tag("oc", "getSeconds", a); };
protoLit.getTime = function (...a: any[]) { return tag("oc", "getTime", a); };
protoLit.getTimezoneOffset = function (...a: any[]) { return tag("oc", "getTimezoneOffset", a); };
protoLit.getUTCDate = function (...a: any[]) { return tag("oc", "getUTCDate", a); };
protoLit.getUTCDay = function (...a: any[]) { return tag("oc", "getUTCDay", a); };
protoLit.getUTCFullYear = function (...a: any[]) { return tag("oc", "getUTCFullYear", a); };
protoLit.getUTCHours = function (...a: any[]) { return tag("oc", "getUTCHours", a); };
protoLit.getUTCMilliseconds = function (...a: any[]) { return tag("oc", "getUTCMilliseconds", a); };
protoLit.getUTCMinutes = function (...a: any[]) { return tag("oc", "getUTCMinutes", a); };
protoLit.getUTCMonth = function (...a: any[]) { return tag("oc", "getUTCMonth", a); };
protoLit.getUTCSeconds = function (...a: any[]) { return tag("oc", "getUTCSeconds", a); };
protoLit.setDate = function (...a: any[]) { return tag("oc", "setDate", a); };
protoLit.setFullYear = function (...a: any[]) { return tag("oc", "setFullYear", a); };
protoLit.setHours = function (...a: any[]) { return tag("oc", "setHours", a); };
protoLit.setMilliseconds = function (...a: any[]) { return tag("oc", "setMilliseconds", a); };
protoLit.setMinutes = function (...a: any[]) { return tag("oc", "setMinutes", a); };
protoLit.setMonth = function (...a: any[]) { return tag("oc", "setMonth", a); };
protoLit.setSeconds = function (...a: any[]) { return tag("oc", "setSeconds", a); };
protoLit.setTime = function (...a: any[]) { return tag("oc", "setTime", a); };
protoLit.setUTCDate = function (...a: any[]) { return tag("oc", "setUTCDate", a); };
protoLit.setUTCFullYear = function (...a: any[]) { return tag("oc", "setUTCFullYear", a); };
protoLit.setUTCHours = function (...a: any[]) { return tag("oc", "setUTCHours", a); };
protoLit.setUTCMilliseconds = function (...a: any[]) { return tag("oc", "setUTCMilliseconds", a); };
protoLit.setUTCMinutes = function (...a: any[]) { return tag("oc", "setUTCMinutes", a); };
protoLit.setUTCMonth = function (...a: any[]) { return tag("oc", "setUTCMonth", a); };
protoLit.setUTCSeconds = function (...a: any[]) { return tag("oc", "setUTCSeconds", a); };
protoLit.toISOString = function (...a: any[]) { return tag("oc", "toISOString", a); };
protoLit.toDateString = function (...a: any[]) { return tag("oc", "toDateString", a); };
protoLit.toTimeString = function (...a: any[]) { return tag("oc", "toTimeString", a); };
protoLit.toUTCString = function (...a: any[]) { return tag("oc", "toUTCString", a); };
protoLit.toGMTString = function (...a: any[]) { return tag("oc", "toGMTString", a); };
protoLit.toLocaleString = function (...a: any[]) { return tag("oc", "toLocaleString", a); };
protoLit.toLocaleDateString = function (...a: any[]) { return tag("oc", "toLocaleDateString", a); };
protoLit.toLocaleTimeString = function (...a: any[]) { return tag("oc", "toLocaleTimeString", a); };
protoLit.toFixed = function (...a: any[]) { return tag("oc", "toFixed", a); };
protoLit.toPrecision = function (...a: any[]) { return tag("oc", "toPrecision", a); };
protoLit.toExponential = function (...a: any[]) { return tag("oc", "toExponential", a); };
protoLit.toSorted = function (...a: any[]) { return tag("oc", "toSorted", a); };
protoLit.toReversed = function (...a: any[]) { return tag("oc", "toReversed", a); };
protoLit.reduceRight = function (...a: any[]) { return tag("oc", "reduceRight", a); };
protoLit.flat = function (...a: any[]) { return tag("oc", "flat", a); };
protoLit.flatMap = function (...a: any[]) { return tag("oc", "flatMap", a); };
protoLit.toSpliced = function (...a: any[]) { return tag("oc", "toSpliced", a); };
protoLit.copyWithin = function (...a: any[]) { return tag("oc", "copyWithin", a); };
protoLit.endsWith = function (...a: any[]) { return tag("oc", "endsWith", a); };
protoLit.includes = function (...a: any[]) { return tag("oc", "includes", a); };
protoLit.startsWith = function (...a: any[]) { return tag("oc", "startsWith", a); };
const oc = Object.create(protoLit);

const f: any = new (F as any)();
const g: any = new (G as any)();

row("getDate()", () => f.getDate(), () => f.viaThis(0), () => g.getDate(), () => lit.getDate(), () => oc.getDate(), () => viaAny(f, 0), () => viaAny(lit, 0), () => viaAny(oc, 0));
row("getDay()", () => f.getDay(), () => f.viaThis(1), () => g.getDay(), () => lit.getDay(), () => oc.getDay(), () => viaAny(f, 1), () => viaAny(lit, 1), () => viaAny(oc, 1));
row("getFullYear()", () => f.getFullYear(), () => f.viaThis(2), () => g.getFullYear(), () => lit.getFullYear(), () => oc.getFullYear(), () => viaAny(f, 2), () => viaAny(lit, 2), () => viaAny(oc, 2));
row("getHours()", () => f.getHours(), () => f.viaThis(3), () => g.getHours(), () => lit.getHours(), () => oc.getHours(), () => viaAny(f, 3), () => viaAny(lit, 3), () => viaAny(oc, 3));
row("getMilliseconds()", () => f.getMilliseconds(), () => f.viaThis(4), () => g.getMilliseconds(), () => lit.getMilliseconds(), () => oc.getMilliseconds(), () => viaAny(f, 4), () => viaAny(lit, 4), () => viaAny(oc, 4));
row("getMinutes()", () => f.getMinutes(), () => f.viaThis(5), () => g.getMinutes(), () => lit.getMinutes(), () => oc.getMinutes(), () => viaAny(f, 5), () => viaAny(lit, 5), () => viaAny(oc, 5));
row("getMonth()", () => f.getMonth(), () => f.viaThis(6), () => g.getMonth(), () => lit.getMonth(), () => oc.getMonth(), () => viaAny(f, 6), () => viaAny(lit, 6), () => viaAny(oc, 6));
row("getSeconds()", () => f.getSeconds(), () => f.viaThis(7), () => g.getSeconds(), () => lit.getSeconds(), () => oc.getSeconds(), () => viaAny(f, 7), () => viaAny(lit, 7), () => viaAny(oc, 7));
row("getTime()", () => f.getTime(), () => f.viaThis(8), () => g.getTime(), () => lit.getTime(), () => oc.getTime(), () => viaAny(f, 8), () => viaAny(lit, 8), () => viaAny(oc, 8));
row("getTimezoneOffset()", () => f.getTimezoneOffset(), () => f.viaThis(9), () => g.getTimezoneOffset(), () => lit.getTimezoneOffset(), () => oc.getTimezoneOffset(), () => viaAny(f, 9), () => viaAny(lit, 9), () => viaAny(oc, 9));
row("getUTCDate()", () => f.getUTCDate(), () => f.viaThis(10), () => g.getUTCDate(), () => lit.getUTCDate(), () => oc.getUTCDate(), () => viaAny(f, 10), () => viaAny(lit, 10), () => viaAny(oc, 10));
row("getUTCDay()", () => f.getUTCDay(), () => f.viaThis(11), () => g.getUTCDay(), () => lit.getUTCDay(), () => oc.getUTCDay(), () => viaAny(f, 11), () => viaAny(lit, 11), () => viaAny(oc, 11));
row("getUTCFullYear()", () => f.getUTCFullYear(), () => f.viaThis(12), () => g.getUTCFullYear(), () => lit.getUTCFullYear(), () => oc.getUTCFullYear(), () => viaAny(f, 12), () => viaAny(lit, 12), () => viaAny(oc, 12));
row("getUTCHours()", () => f.getUTCHours(), () => f.viaThis(13), () => g.getUTCHours(), () => lit.getUTCHours(), () => oc.getUTCHours(), () => viaAny(f, 13), () => viaAny(lit, 13), () => viaAny(oc, 13));
row("getUTCMilliseconds()", () => f.getUTCMilliseconds(), () => f.viaThis(14), () => g.getUTCMilliseconds(), () => lit.getUTCMilliseconds(), () => oc.getUTCMilliseconds(), () => viaAny(f, 14), () => viaAny(lit, 14), () => viaAny(oc, 14));
row("getUTCMinutes()", () => f.getUTCMinutes(), () => f.viaThis(15), () => g.getUTCMinutes(), () => lit.getUTCMinutes(), () => oc.getUTCMinutes(), () => viaAny(f, 15), () => viaAny(lit, 15), () => viaAny(oc, 15));
row("getUTCMonth()", () => f.getUTCMonth(), () => f.viaThis(16), () => g.getUTCMonth(), () => lit.getUTCMonth(), () => oc.getUTCMonth(), () => viaAny(f, 16), () => viaAny(lit, 16), () => viaAny(oc, 16));
row("getUTCSeconds()", () => f.getUTCSeconds(), () => f.viaThis(17), () => g.getUTCSeconds(), () => lit.getUTCSeconds(), () => oc.getUTCSeconds(), () => viaAny(f, 17), () => viaAny(lit, 17), () => viaAny(oc, 17));
row("setDate(1)", () => f.setDate(1), () => f.viaThis(18), () => g.setDate(1), () => lit.setDate(1), () => oc.setDate(1), () => viaAny(f, 18), () => viaAny(lit, 18), () => viaAny(oc, 18));
row("setFullYear(1)", () => f.setFullYear(1), () => f.viaThis(19), () => g.setFullYear(1), () => lit.setFullYear(1), () => oc.setFullYear(1), () => viaAny(f, 19), () => viaAny(lit, 19), () => viaAny(oc, 19));
row("setHours(1)", () => f.setHours(1), () => f.viaThis(20), () => g.setHours(1), () => lit.setHours(1), () => oc.setHours(1), () => viaAny(f, 20), () => viaAny(lit, 20), () => viaAny(oc, 20));
row("setMilliseconds(1)", () => f.setMilliseconds(1), () => f.viaThis(21), () => g.setMilliseconds(1), () => lit.setMilliseconds(1), () => oc.setMilliseconds(1), () => viaAny(f, 21), () => viaAny(lit, 21), () => viaAny(oc, 21));
row("setMinutes(1)", () => f.setMinutes(1), () => f.viaThis(22), () => g.setMinutes(1), () => lit.setMinutes(1), () => oc.setMinutes(1), () => viaAny(f, 22), () => viaAny(lit, 22), () => viaAny(oc, 22));
row("setMonth(1)", () => f.setMonth(1), () => f.viaThis(23), () => g.setMonth(1), () => lit.setMonth(1), () => oc.setMonth(1), () => viaAny(f, 23), () => viaAny(lit, 23), () => viaAny(oc, 23));
row("setSeconds(1)", () => f.setSeconds(1), () => f.viaThis(24), () => g.setSeconds(1), () => lit.setSeconds(1), () => oc.setSeconds(1), () => viaAny(f, 24), () => viaAny(lit, 24), () => viaAny(oc, 24));
row("setTime(1)", () => f.setTime(1), () => f.viaThis(25), () => g.setTime(1), () => lit.setTime(1), () => oc.setTime(1), () => viaAny(f, 25), () => viaAny(lit, 25), () => viaAny(oc, 25));
row("setUTCDate(1)", () => f.setUTCDate(1), () => f.viaThis(26), () => g.setUTCDate(1), () => lit.setUTCDate(1), () => oc.setUTCDate(1), () => viaAny(f, 26), () => viaAny(lit, 26), () => viaAny(oc, 26));
row("setUTCFullYear(1)", () => f.setUTCFullYear(1), () => f.viaThis(27), () => g.setUTCFullYear(1), () => lit.setUTCFullYear(1), () => oc.setUTCFullYear(1), () => viaAny(f, 27), () => viaAny(lit, 27), () => viaAny(oc, 27));
row("setUTCHours(1)", () => f.setUTCHours(1), () => f.viaThis(28), () => g.setUTCHours(1), () => lit.setUTCHours(1), () => oc.setUTCHours(1), () => viaAny(f, 28), () => viaAny(lit, 28), () => viaAny(oc, 28));
row("setUTCMilliseconds(1)", () => f.setUTCMilliseconds(1), () => f.viaThis(29), () => g.setUTCMilliseconds(1), () => lit.setUTCMilliseconds(1), () => oc.setUTCMilliseconds(1), () => viaAny(f, 29), () => viaAny(lit, 29), () => viaAny(oc, 29));
row("setUTCMinutes(1)", () => f.setUTCMinutes(1), () => f.viaThis(30), () => g.setUTCMinutes(1), () => lit.setUTCMinutes(1), () => oc.setUTCMinutes(1), () => viaAny(f, 30), () => viaAny(lit, 30), () => viaAny(oc, 30));
row("setUTCMonth(1)", () => f.setUTCMonth(1), () => f.viaThis(31), () => g.setUTCMonth(1), () => lit.setUTCMonth(1), () => oc.setUTCMonth(1), () => viaAny(f, 31), () => viaAny(lit, 31), () => viaAny(oc, 31));
row("setUTCSeconds(1)", () => f.setUTCSeconds(1), () => f.viaThis(32), () => g.setUTCSeconds(1), () => lit.setUTCSeconds(1), () => oc.setUTCSeconds(1), () => viaAny(f, 32), () => viaAny(lit, 32), () => viaAny(oc, 32));
row("toISOString()", () => f.toISOString(), () => f.viaThis(33), () => g.toISOString(), () => lit.toISOString(), () => oc.toISOString(), () => viaAny(f, 33), () => viaAny(lit, 33), () => viaAny(oc, 33));
row("toDateString()", () => f.toDateString(), () => f.viaThis(34), () => g.toDateString(), () => lit.toDateString(), () => oc.toDateString(), () => viaAny(f, 34), () => viaAny(lit, 34), () => viaAny(oc, 34));
row("toTimeString()", () => f.toTimeString(), () => f.viaThis(35), () => g.toTimeString(), () => lit.toTimeString(), () => oc.toTimeString(), () => viaAny(f, 35), () => viaAny(lit, 35), () => viaAny(oc, 35));
row("toUTCString()", () => f.toUTCString(), () => f.viaThis(36), () => g.toUTCString(), () => lit.toUTCString(), () => oc.toUTCString(), () => viaAny(f, 36), () => viaAny(lit, 36), () => viaAny(oc, 36));
row("toGMTString()", () => f.toGMTString(), () => f.viaThis(37), () => g.toGMTString(), () => lit.toGMTString(), () => oc.toGMTString(), () => viaAny(f, 37), () => viaAny(lit, 37), () => viaAny(oc, 37));
row("toLocaleString()", () => f.toLocaleString(), () => f.viaThis(38), () => g.toLocaleString(), () => lit.toLocaleString(), () => oc.toLocaleString(), () => viaAny(f, 38), () => viaAny(lit, 38), () => viaAny(oc, 38));
row("toLocaleDateString()", () => f.toLocaleDateString(), () => f.viaThis(39), () => g.toLocaleDateString(), () => lit.toLocaleDateString(), () => oc.toLocaleDateString(), () => viaAny(f, 39), () => viaAny(lit, 39), () => viaAny(oc, 39));
row("toLocaleTimeString()", () => f.toLocaleTimeString(), () => f.viaThis(40), () => g.toLocaleTimeString(), () => lit.toLocaleTimeString(), () => oc.toLocaleTimeString(), () => viaAny(f, 40), () => viaAny(lit, 40), () => viaAny(oc, 40));
row("toFixed(2)", () => f.toFixed(2), () => f.viaThis(41), () => g.toFixed(2), () => lit.toFixed(2), () => oc.toFixed(2), () => viaAny(f, 41), () => viaAny(lit, 41), () => viaAny(oc, 41));
row("toPrecision(2)", () => f.toPrecision(2), () => f.viaThis(42), () => g.toPrecision(2), () => lit.toPrecision(2), () => oc.toPrecision(2), () => viaAny(f, 42), () => viaAny(lit, 42), () => viaAny(oc, 42));
row("toExponential(2)", () => f.toExponential(2), () => f.viaThis(43), () => g.toExponential(2), () => lit.toExponential(2), () => oc.toExponential(2), () => viaAny(f, 43), () => viaAny(lit, 43), () => viaAny(oc, 43));
row("toFixed()", () => f.toFixed(), () => f.viaThis(44), () => g.toFixed(), () => lit.toFixed(), () => oc.toFixed(), () => viaAny(f, 44), () => viaAny(lit, 44), () => viaAny(oc, 44));
row("toSorted()", () => f.toSorted(), () => f.viaThis(45), () => g.toSorted(), () => lit.toSorted(), () => oc.toSorted(), () => viaAny(f, 45), () => viaAny(lit, 45), () => viaAny(oc, 45));
row("toSorted(cmp)", () => f.toSorted(cmp), () => f.viaThis(46), () => g.toSorted(cmp), () => lit.toSorted(cmp), () => oc.toSorted(cmp), () => viaAny(f, 46), () => viaAny(lit, 46), () => viaAny(oc, 46));
row("toReversed()", () => f.toReversed(), () => f.viaThis(47), () => g.toReversed(), () => lit.toReversed(), () => oc.toReversed(), () => viaAny(f, 47), () => viaAny(lit, 47), () => viaAny(oc, 47));
row("reduceRight(add)", () => f.reduceRight(add), () => f.viaThis(48), () => g.reduceRight(add), () => lit.reduceRight(add), () => oc.reduceRight(add), () => viaAny(f, 48), () => viaAny(lit, 48), () => viaAny(oc, 48));
row("flat()", () => f.flat(), () => f.viaThis(49), () => g.flat(), () => lit.flat(), () => oc.flat(), () => viaAny(f, 49), () => viaAny(lit, 49), () => viaAny(oc, 49));
row("flatMap(dup)", () => f.flatMap(dup), () => f.viaThis(50), () => g.flatMap(dup), () => lit.flatMap(dup), () => oc.flatMap(dup), () => viaAny(f, 50), () => viaAny(lit, 50), () => viaAny(oc, 50));
row("toSpliced(1)", () => f.toSpliced(1), () => f.viaThis(51), () => g.toSpliced(1), () => lit.toSpliced(1), () => oc.toSpliced(1), () => viaAny(f, 51), () => viaAny(lit, 51), () => viaAny(oc, 51));
row("toSpliced(0, 1)", () => f.toSpliced(0, 1), () => f.viaThis(52), () => g.toSpliced(0, 1), () => lit.toSpliced(0, 1), () => oc.toSpliced(0, 1), () => viaAny(f, 52), () => viaAny(lit, 52), () => viaAny(oc, 52));
row("copyWithin(0, 1)", () => f.copyWithin(0, 1), () => f.viaThis(53), () => g.copyWithin(0, 1), () => lit.copyWithin(0, 1), () => oc.copyWithin(0, 1), () => viaAny(f, 53), () => viaAny(lit, 53), () => viaAny(oc, 53));
row("endsWith()", () => f.endsWith(), () => f.viaThis(54), () => g.endsWith(), () => lit.endsWith(), () => oc.endsWith(), () => viaAny(f, 54), () => viaAny(lit, 54), () => viaAny(oc, 54));
row("includes()", () => f.includes(), () => f.viaThis(55), () => g.includes(), () => lit.includes(), () => oc.includes(), () => viaAny(f, 55), () => viaAny(lit, 55), () => viaAny(oc, 55));
row("startsWith()", () => f.startsWith(), () => f.viaThis(56), () => g.startsWith(), () => lit.startsWith(), () => oc.startsWith(), () => viaAny(f, 56), () => viaAny(lit, 56), () => viaAny(oc, 56));
row("endsWith('c')", () => f.endsWith('c'), () => f.viaThis(57), () => g.endsWith('c'), () => lit.endsWith('c'), () => oc.endsWith('c'), () => viaAny(f, 57), () => viaAny(lit, 57), () => viaAny(oc, 57));
row("includes('b')", () => f.includes('b'), () => f.viaThis(58), () => g.includes('b'), () => lit.includes('b'), () => oc.includes('b'), () => viaAny(f, 58), () => viaAny(lit, 58), () => viaAny(oc, 58));
row("startsWith('a')", () => f.startsWith('a'), () => f.viaThis(59), () => g.startsWith('a'), () => lit.startsWith('a'), () => oc.startsWith('a'), () => viaAny(f, 59), () => viaAny(lit, 59), () => viaAny(oc, 59));

// dayjs / moment `toJSON` shape: a prototype method calls a sibling via `this`.
function Dayjs(this: any, ms: number) { this.$d = new Date(ms); }
Dayjs.prototype.isValid = function () { return true; };
Dayjs.prototype.toISOString = function (this: any) { return "Dayjs(" + this.$d.toISOString() + ")"; };
Dayjs.prototype.valueOf = function (this: any) { return this.$d.getTime(); };
Dayjs.prototype.toJSON = function (this: any) { return this.isValid() ? this.toISOString() : null; };
const dj: any = new (Dayjs as any)(7);
console.log("dayjs toJSON", dj.toJSON(), JSON.stringify({ at: dj }), +dj);

// Controls: the real built-ins on typed receivers, `any` receivers and the
// shared `viaAny` call sites. Local-time results depend on the host zone, so
// local getters/setters are compared with UTC-derived values, not printed.
const d = new Date(Date.UTC(2024, 5, 15, 10, 20, 30, 456));
const du: any = new Date(Date.UTC(2024, 5, 15, 10, 20, 30, 456));
const shifted = new Date(d.getTime() - d.getTimezoneOffset() * 60000);
console.log("Date getDate", d.getDate() === shifted.getUTCDate(), du.getDate() === d.getDate(), viaAny(du, 0) === d.getDate());
console.log("Date getDay", d.getDay() === shifted.getUTCDay(), du.getDay() === d.getDay(), viaAny(du, 1) === d.getDay());
console.log("Date getFullYear", d.getFullYear() === shifted.getUTCFullYear(), du.getFullYear() === d.getFullYear(), viaAny(du, 2) === d.getFullYear());
console.log("Date getHours", d.getHours() === shifted.getUTCHours(), du.getHours() === d.getHours(), viaAny(du, 3) === d.getHours());
console.log("Date getMilliseconds", d.getMilliseconds() === shifted.getUTCMilliseconds(), du.getMilliseconds() === d.getMilliseconds(), viaAny(du, 4) === d.getMilliseconds());
console.log("Date getMinutes", d.getMinutes() === shifted.getUTCMinutes(), du.getMinutes() === d.getMinutes(), viaAny(du, 5) === d.getMinutes());
console.log("Date getMonth", d.getMonth() === shifted.getUTCMonth(), du.getMonth() === d.getMonth(), viaAny(du, 6) === d.getMonth());
console.log("Date getSeconds", d.getSeconds() === shifted.getUTCSeconds(), du.getSeconds() === d.getSeconds(), viaAny(du, 7) === d.getSeconds());
console.log("Date getTime", d.getTime(), du.getTime(), viaAny(du, 8));
console.log("Date getTimezoneOffset", typeof d.getTimezoneOffset(), du.getTimezoneOffset() === d.getTimezoneOffset(), viaAny(du, 9) === d.getTimezoneOffset());
console.log("Date getUTCDate", d.getUTCDate(), du.getUTCDate(), viaAny(du, 10));
console.log("Date getUTCDay", d.getUTCDay(), du.getUTCDay(), viaAny(du, 11));
console.log("Date getUTCFullYear", d.getUTCFullYear(), du.getUTCFullYear(), viaAny(du, 12));
console.log("Date getUTCHours", d.getUTCHours(), du.getUTCHours(), viaAny(du, 13));
console.log("Date getUTCMilliseconds", d.getUTCMilliseconds(), du.getUTCMilliseconds(), viaAny(du, 14));
console.log("Date getUTCMinutes", d.getUTCMinutes(), du.getUTCMinutes(), viaAny(du, 15));
console.log("Date getUTCMonth", d.getUTCMonth(), du.getUTCMonth(), viaAny(du, 16));
console.log("Date getUTCSeconds", d.getUTCSeconds(), du.getUTCSeconds(), viaAny(du, 17));
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  const r = [t.setDate(1), tu.setDate(1), viaAny(tv, 18)];
  console.log("Date setDate", typeof r[0], r[0] === t.getTime(), r[1] === tu.getTime(), r[2] === tv.getTime(), t.getDate(), tu.getDate(), tv.getDate()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  const r = [t.setFullYear(1), tu.setFullYear(1), viaAny(tv, 19)];
  console.log("Date setFullYear", typeof r[0], r[0] === t.getTime(), r[1] === tu.getTime(), r[2] === tv.getTime(), t.getFullYear(), tu.getFullYear(), tv.getFullYear()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  const r = [t.setHours(1), tu.setHours(1), viaAny(tv, 20)];
  console.log("Date setHours", typeof r[0], r[0] === t.getTime(), r[1] === tu.getTime(), r[2] === tv.getTime(), t.getHours(), tu.getHours(), tv.getHours()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  const r = [t.setMilliseconds(1), tu.setMilliseconds(1), viaAny(tv, 21)];
  console.log("Date setMilliseconds", typeof r[0], r[0] === t.getTime(), r[1] === tu.getTime(), r[2] === tv.getTime(), t.getMilliseconds(), tu.getMilliseconds(), tv.getMilliseconds()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  const r = [t.setMinutes(1), tu.setMinutes(1), viaAny(tv, 22)];
  console.log("Date setMinutes", typeof r[0], r[0] === t.getTime(), r[1] === tu.getTime(), r[2] === tv.getTime(), t.getMinutes(), tu.getMinutes(), tv.getMinutes()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  const r = [t.setMonth(1), tu.setMonth(1), viaAny(tv, 23)];
  console.log("Date setMonth", typeof r[0], r[0] === t.getTime(), r[1] === tu.getTime(), r[2] === tv.getTime(), t.getMonth(), tu.getMonth(), tv.getMonth()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  const r = [t.setSeconds(1), tu.setSeconds(1), viaAny(tv, 24)];
  console.log("Date setSeconds", typeof r[0], r[0] === t.getTime(), r[1] === tu.getTime(), r[2] === tv.getTime(), t.getSeconds(), tu.getSeconds(), tv.getSeconds()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setTime", t.setTime(1), t.getTime(), tu.setTime(1), tu.getTime(), viaAny(tv, 25), tv.getTime()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setUTCDate", t.setUTCDate(1), t.getTime(), tu.setUTCDate(1), tu.getTime(), viaAny(tv, 26), tv.getTime()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setUTCFullYear", t.setUTCFullYear(1), t.getTime(), tu.setUTCFullYear(1), tu.getTime(), viaAny(tv, 27), tv.getTime()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setUTCHours", t.setUTCHours(1), t.getTime(), tu.setUTCHours(1), tu.getTime(), viaAny(tv, 28), tv.getTime()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setUTCMilliseconds", t.setUTCMilliseconds(1), t.getTime(), tu.setUTCMilliseconds(1), tu.getTime(), viaAny(tv, 29), tv.getTime()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setUTCMinutes", t.setUTCMinutes(1), t.getTime(), tu.setUTCMinutes(1), tu.getTime(), viaAny(tv, 30), tv.getTime()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setUTCMonth", t.setUTCMonth(1), t.getTime(), tu.setUTCMonth(1), tu.getTime(), viaAny(tv, 31), tv.getTime()); }
{ const t = new Date(d.getTime()); const tu: any = new Date(d.getTime()); const tv = new Date(d.getTime());
  console.log("Date setUTCSeconds", t.setUTCSeconds(1), t.getTime(), tu.setUTCSeconds(1), tu.getTime(), viaAny(tv, 32), tv.getTime()); }
console.log("Date toISOString", d.toISOString(), du.toISOString(), viaAny(du, 33));
console.log("Date toUTCString", d.toUTCString(), du.toUTCString(), viaAny(du, 36));
console.log("Date toGMTString", d.toGMTString(), du.toGMTString(), viaAny(du, 37));
console.log("Date toDateString", typeof d.toDateString(), du.toDateString() === d.toDateString(), viaAny(du, 34) === d.toDateString());
console.log("Date toTimeString", typeof d.toTimeString(), du.toTimeString() === d.toTimeString(), viaAny(du, 35) === d.toTimeString());
console.log("Date toLocaleString", typeof d.toLocaleString(), du.toLocaleString() === d.toLocaleString(), viaAny(du, 38) === d.toLocaleString());
console.log("Date toLocaleDateString", typeof d.toLocaleDateString(), du.toLocaleDateString() === d.toLocaleDateString(), viaAny(du, 39) === d.toLocaleDateString());
console.log("Date toLocaleTimeString", typeof d.toLocaleTimeString(), du.toLocaleTimeString() === d.toLocaleTimeString(), viaAny(du, 40) === d.toLocaleTimeString());
// Zero-argument toLocaleString on primitives and symbols is Object.prototype's.
console.log("primitive toLocaleString", viaAny(true, 38), viaAny("abc", 38), viaAny(Symbol("s"), 38));
const bad: any = new Date(NaN);
console.log("Invalid Date toISOString", attemptMessage(() => bad.toISOString()), attemptMessage(() => viaAny(bad, 33)));
const num = 3.14159;
const numu: any = 1234.5678;
console.log("number toFixed(2)", num.toFixed(2), numu.toFixed(2), viaAny(num, 41), viaAny(42, 41), viaAny(-0.5, 41));
console.log("number toFixed()", num.toFixed(), numu.toFixed(), viaAny(num, 44), viaAny(42, 44), viaAny(-0.5, 44));
console.log("number toPrecision(2)", num.toPrecision(2), numu.toPrecision(2), viaAny(num, 42), viaAny(42, 42), viaAny(-0.5, 42));
console.log("number toExponential(2)", num.toExponential(2), numu.toExponential(2), viaAny(num, 43), viaAny(42, 43), viaAny(-0.5, 43));
const arr = [3, 1, 2];
const arru: any = [5, 4, 6];
const nested = [1, [2, [3]]];
const nestedu: any = [4, [5, [6]]];
console.log("array toSorted()", show(arr.toSorted()), show(arru.toSorted()), show(viaAny(arr, 45)), show(arr));
console.log("array toSorted(cmp)", show(arr.toSorted(cmp)), show(arru.toSorted(cmp)), show(viaAny(arr, 46)), show(arr));
console.log("array toReversed()", show(arr.toReversed()), show(arru.toReversed()), show(viaAny(arr, 47)), show(arr));
console.log("array reduceRight(add)", show(arr.reduceRight(add)), show(arru.reduceRight(add)), show(viaAny(arr, 48)), show(arr));
console.log("array flat()", show(nested.flat()), show(nestedu.flat()), show(viaAny(nested, 49)));
console.log("array flatMap(dup)", show(arr.flatMap(dup)), show(arru.flatMap(dup)), show(viaAny(arr, 50)), show(arr));
console.log("array toSpliced(1)", show(arr.toSpliced(1)), show(arru.toSpliced(1)), show(viaAny(arr, 51)), show(arr));
console.log("array toSpliced(0, 1)", show(arr.toSpliced(0, 1)), show(arru.toSpliced(0, 1)), show(viaAny(arr, 52)), show(arr));
console.log("array copyWithin(0, 1)", show([3, 1, 2].copyWithin(0, 1)), show(arru.slice().copyWithin(0, 1)), show(viaAny([7, 8, 9], 53)));
const str = "abc";
const stru: any = "xundefined";
console.log("string endsWith()", str.endsWith(), stru.endsWith(), viaAny(str, 54), viaAny(stru, 54));
console.log("string endsWith('c')", str.endsWith('c'), stru.endsWith('c'), viaAny(str, 57), viaAny(stru, 57));
console.log("string includes()", str.includes(), stru.includes(), viaAny(str, 55), viaAny(stru, 55));
console.log("string includes('b')", str.includes('b'), stru.includes('b'), viaAny(str, 58), viaAny(stru, 58));
console.log("string startsWith()", str.startsWith(), stru.startsWith(), viaAny(str, 56), viaAny(stru, 56));
console.log("string startsWith('a')", str.startsWith('a'), stru.startsWith('a'), viaAny(str, 59), viaAny(stru, 59));

// One call site per name, the matching built-in and user objects in turn.
for (const m of [new Date(Date.UTC(2020, 0, 1)), f, g, lit, oc] as any[]) row("mixed getTime", () => viaAny(m, 8));
for (const m of [new Date(0), f, g, lit, oc] as any[]) row("mixed toISOString", () => viaAny(m, 33));
for (const m of [new Date(0), f, g, lit, oc] as any[]) row("mixed setUTCHours", () => viaAny(m, 28));
for (const m of [12.345, f, g, lit, oc] as any[]) row("mixed toFixed", () => viaAny(m, 41));
for (const m of [-7, f, g, lit, oc] as any[]) row("mixed toPrecision", () => viaAny(m, 42));
for (const m of [[2, 1], f, g, lit, oc] as any[]) row("mixed toSorted", () => viaAny(m, 45));
for (const m of [[[1], 2], f, g, lit, oc] as any[]) row("mixed flat", () => viaAny(m, 49));
for (const m of ["abc", f, g, lit, oc] as any[]) row("mixed endsWith", () => viaAny(m, 54));

// A builtin-named user method may return anything; its result must not be
// treated as the builtin's string / number result.
const odd: any = {
  toFixed(dp: number) { return 5 + dp; },
  toPrecision() { return { p: 1 }; },
  toExponential() { return null; },
  getTime() { return "t"; },
  toISOString() { return 42; },
};
console.log("odd", "a" + odd.toFixed(2), odd.toFixed(2) + 1, typeof odd.toFixed(2), JSON.stringify(odd.toPrecision(3)));
console.log("odd", "c" + odd.toExponential(1), odd.getTime() + 1, odd.toISOString() + 1, `${odd.toFixed(4)}!`);
let oddAcc = "";
for (let i = 0; i < 3; i++) oddAcc += odd.toFixed(i);
console.log("odd loop", oddAcc);

// Nullish receivers throw instead of reaching a builtin.
const nothing: any = null;
console.log("nullish", attemptMessage(() => nothing.getTime()), attemptMessage(() => nothing.toFixed(1)));
