// #11256: instanceof follows prototype chains, independently of native brands.
console.log("Map", Object.create(Map.prototype) instanceof Map);
console.log("Set", Object.create(Set.prototype) instanceof Set);
console.log("Date", Object.create(Date.prototype) instanceof Date);
console.log("RegExp", Object.create(RegExp.prototype) instanceof RegExp);
console.log("ArrayBuffer", Object.create(ArrayBuffer.prototype) instanceof ArrayBuffer);
console.log("SharedArrayBuffer", Object.create(SharedArrayBuffer.prototype) instanceof SharedArrayBuffer);
console.log("Buffer", Object.create(Buffer.prototype) instanceof Buffer);
console.log("Int8Array", Object.create(Int8Array.prototype) instanceof Int8Array);
console.log("Uint8Array", Object.create(Uint8Array.prototype) instanceof Uint8Array);
console.log("Uint8ClampedArray", Object.create(Uint8ClampedArray.prototype) instanceof Uint8ClampedArray);
console.log("Int16Array", Object.create(Int16Array.prototype) instanceof Int16Array);
console.log("Uint16Array", Object.create(Uint16Array.prototype) instanceof Uint16Array);
console.log("Int32Array", Object.create(Int32Array.prototype) instanceof Int32Array);
console.log("Uint32Array", Object.create(Uint32Array.prototype) instanceof Uint32Array);
console.log("Float16Array", Object.create(Float16Array.prototype) instanceof Float16Array);
console.log("Float32Array", Object.create(Float32Array.prototype) instanceof Float32Array);
console.log("Float64Array", Object.create(Float64Array.prototype) instanceof Float64Array);
console.log("BigInt64Array", Object.create(BigInt64Array.prototype) instanceof BigInt64Array);
console.log("BigUint64Array", Object.create(BigUint64Array.prototype) instanceof BigUint64Array);
console.log("Error", Object.create(Error.prototype) instanceof Error);
console.log("TypeError", Object.create(TypeError.prototype) instanceof TypeError);
console.log("RangeError", Object.create(RangeError.prototype) instanceof RangeError);
console.log("ReferenceError", Object.create(ReferenceError.prototype) instanceof ReferenceError);
console.log("SyntaxError", Object.create(SyntaxError.prototype) instanceof SyntaxError);
console.log("EvalError", Object.create(EvalError.prototype) instanceof EvalError);
console.log("URIError", Object.create(URIError.prototype) instanceof URIError);
console.log("AggregateError", Object.create(AggregateError.prototype) instanceof AggregateError);
console.log("indirect", Object.create(Object.create(Map.prototype)) instanceof Map);
console.log("buffer parent", Buffer.prototype instanceof Uint8Array);
console.log("wrong prototype", Object.create(Map.prototype) instanceof Set);
console.log("null prototype", Object.create(null) instanceof Map);
console.log("self prototype", Map.prototype instanceof Map);
console.log("number", 42 instanceof Map);
console.log("real map", new Map() instanceof Map);
console.log("real set", new Set() instanceof Set);
console.log("real view", new Uint8Array(2) instanceof Uint8Array);
class Control {}
console.log("user class", Object.create(Control.prototype) instanceof Control);
