// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:readline/promises
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_readline_promises` to verify.

import * as readline_promises from "node:readline/promises";
import { Readable } from "node:stream";

// readline_promises.createInterface(options)
// Feed an in-memory Readable so the harness never blocks on real stdin.
try {
  const r = Readable.from(["line1\nline2\n"]);
  const rl = readline_promises.createInterface({ input: r, output: process.stdout, terminal: false });
  console.log("createInterface typeof:", typeof rl);
  console.log("rl.close typeof:", typeof rl.close);
  console.log("rl.question typeof:", typeof rl.question);
  rl.close();
  console.log("rl.close() invoked:", true);
} catch (e) {
  console.log("createInterface threw");
}
// PERRY-SKIP: rl.question() — would consume from input + return a Promise; covered by the gap-suite readline tests that exercise behavior end-to-end.
// PERRY-SKIP: class Readline / rl.clearLine / clearScreenDown / cursorTo / moveCursor / commit / rollback — require terminal-mode output, emit ANSI escapes that diverge by terminal type.

// Coverage: 0 auto-emitted, 1 TODO, 0 skip-listed.
