// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:timers/promises
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_timers_promises` to verify.

import * as timers_promises from "node:timers/promises";

async function main() {
  // ── exports ──
  try {
    console.log("setTimeout typeof:", typeof timers_promises.setTimeout);
    console.log("setImmediate typeof:", typeof timers_promises.setImmediate);
    console.log("setInterval typeof:", typeof timers_promises.setInterval);
  } catch (e) {
    console.log("exports error:", (e as Error).message);
  }

  // ── setTimeout(delay, value) ──
  try {
    const v = await timers_promises.setTimeout(0, "value");
    console.log("setTimeout result:", v);
  } catch (e) {
    console.log("setTimeout error:", (e as Error).message);
  }

  // ── setImmediate(value) ──
  try {
    const v = await timers_promises.setImmediate("imm-value");
    console.log("setImmediate result:", v);
  } catch (e) {
    console.log("setImmediate error:", (e as Error).message);
  }

  // ── setInterval async iter ──
  try {
    let count = 0;
    for await (const _ of timers_promises.setInterval(0, "tick")) {
      count++;
      break;
    }
    console.log("setInterval iter count:", count);
  } catch (e) {
    console.log("setInterval error:", (e as Error).message);
  }
}

main();

// Coverage: 0 auto-emitted, 5 TODO, 0 skip-listed.
