// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:tty
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_tty` to verify.

import * as tty from "node:tty";


// ── Functions ──
try {
  console.log("tty.isatty(0):", tty.isatty(0));
  console.log("tty.isatty(1):", tty.isatty(1));
  console.log("tty.isatty(2):", tty.isatty(2));
} catch (e) {
  console.log("tty.isatty threw");
}

// ── Class: tty.ReadStream (extends net.Socket) ──
try {
  console.log("tty.ReadStream typeof:", typeof tty.ReadStream);
} catch (e) {
  console.log("tty.ReadStream threw");
}
// SKIP: new tty.ReadStream(fd[, options]) — opening a real TTY requires a terminal; non-deterministic under piped stdin.
// SKIP: readStream.isRaw — instance-only; needs constructed ReadStream.
// SKIP: readStream.isTTY — instance-only.
// SKIP: readStream.fd — instance-only.
// SKIP: readStream.setRawMode(mode) — instance-only; mutates terminal state.

// ── Class: tty.WriteStream (extends net.Socket) ──
try {
  console.log("tty.WriteStream typeof:", typeof tty.WriteStream);
} catch (e) {
  console.log("tty.WriteStream threw");
}
// SKIP: new tty.WriteStream(fd) — opening a real TTY requires a terminal; non-deterministic under piped stdout.
try {
  console.log("process.stdout.isTTY typeof:", typeof process.stdout.isTTY);
} catch (e) {
  console.log("process.stdout.isTTY threw");
}
// SKIP: writeStream.fd — instance-only; numeric value 1 on stdout but depends on construction.
try {
  console.log("process.stdout.columns typeof:", typeof process.stdout.columns);
} catch (e) {
  console.log("process.stdout.columns threw");
}
try {
  console.log("process.stdout.rows typeof:", typeof process.stdout.rows);
} catch (e) {
  console.log("process.stdout.rows threw");
}
// SKIP: writeStream.clearLine(dir[, callback]) — emits raw ANSI to stdout (would pollute parity output).
// SKIP: writeStream.clearScreenDown([callback]) — emits raw ANSI to stdout.
// SKIP: writeStream.cursorTo(x[, y][, callback]) — emits raw ANSI to stdout.
// SKIP: writeStream.moveCursor(dx, dy[, callback]) — emits raw ANSI to stdout.
// SKIP: writeStream.getWindowSize() — non-deterministic under piped stdout (returns undefined or [cols,rows]).
try {
  console.log("process.stdout.getColorDepth typeof:", typeof process.stdout.getColorDepth);
} catch (e) {
  console.log("process.stdout.getColorDepth threw");
}
try {
  console.log("process.stdout.hasColors typeof:", typeof process.stdout.hasColors);
} catch (e) {
  console.log("process.stdout.hasColors threw");
}

// ── Events on WriteStream ──
// SKIP: 'resize' — async event, never fires under piped stdout / non-interactive runs.

// Coverage: 0 auto-emitted, 19 TODO, 0 skip-listed.
