// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:sys (deprecated alias for node:util)
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.

import * as sys from "node:sys";
import * as util from "node:util";

// node:sys is documented as a deprecated alias of node:util — same surface.
try {
  console.log("sys.format type:", typeof sys.format);
  console.log("util.format type:", typeof util.format);
  console.log("sys.format === util.format:", sys.format === util.format);
  console.log("sys.inspect type:", typeof sys.inspect);
  console.log("sys.inspect === util.inspect:", sys.inspect === util.inspect);
} catch (e) {
  console.log("sys ERROR:", (e as Error).message);
}
