// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:os
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_os` to verify.

import * as os from "node:os";


// ── Functions ──
console.log("os.arch():", os.arch());
// PERRY-SKIP: os.availableParallelism — not yet implemented in Perry (#463 gate).
// SKIP: os.cpus() — CPU model strings + counters — host-dependent.
// PERRY-SKIP: os.endianness — not yet implemented in Perry (#463 gate).
// SKIP: os.freemem() — Free memory — non-deterministic value.
// PERRY-SKIP: os.getPriority — not yet implemented in Perry (#463 gate).
// SKIP: os.homedir() — Per-user homedir — host-dependent.
// SKIP: os.hostname() — Per-host name — host-dependent.
// SKIP: os.loadavg() — Load averages — non-deterministic value.
// SKIP: os.machine() — CPU architecture details — host-dependent.
// SKIP: os.networkInterfaces() — Per-host network configuration — host-dependent.
console.log("os.platform():", os.platform());
console.log("os.release():", os.release());
// SKIP: os.setPriority — host-dependent / requires permissions.
// SKIP: os.tmpdir() — Per-host tmpdir — host-dependent.
// SKIP: os.totalmem() — Total memory — host-dependent value.
console.log("os.type():", os.type());
// SKIP: os.uptime() — Host uptime — non-deterministic value.
// SKIP: os.userInfo([options]) — Per-user info — host-dependent.
// PERRY-SKIP: os.version — not yet implemented in Perry (#463 gate).

// ── Properties ──
console.log("EOL is LF:", os.EOL === "\n");
// SKIP: os.devNull — host-dependent (/dev/null vs \\\\.\\nul).
// SKIP: os.constants — entire object; specific constants probed below.

// ── Signal Constants (`os.constants.signals`) ──
// SKIP: SIGHUP — host-dependent numeric value.
try { console.log("SIGINT:", os.constants.signals.SIGINT); } catch (e) { console.log("SIGINT threw"); }
// SKIP: SIGQUIT — host-dependent.
// SKIP: SIGILL — host-dependent.
// SKIP: SIGTRAP — host-dependent.
// SKIP: SIGABRT — host-dependent.
// SKIP: SIGIOT — host-dependent.
// SKIP: SIGBUS — host-dependent.
// SKIP: SIGFPE — host-dependent.
// SKIP: SIGKILL — host-dependent.
// SKIP: SIGUSR1 — host-dependent.
// SKIP: SIGUSR2 — host-dependent.
// SKIP: SIGSEGV — host-dependent.
// SKIP: SIGPIPE — host-dependent.
// SKIP: SIGALRM — host-dependent.
// SKIP: SIGTERM — host-dependent.
// SKIP: SIGCHLD — host-dependent.
// SKIP: SIGSTKFLT — Linux-only.
// SKIP: SIGCONT — host-dependent.
// SKIP: SIGSTOP — host-dependent.
// SKIP: SIGTSTP — host-dependent.
// SKIP: SIGBREAK — Windows-only.
// SKIP: SIGTTIN — host-dependent.
// SKIP: SIGTTOU — host-dependent.
// SKIP: SIGURG — host-dependent.
// SKIP: SIGXCPU — host-dependent.
// SKIP: SIGXFSZ — host-dependent.
// SKIP: SIGVTALRM — host-dependent.
// SKIP: SIGPROF — host-dependent.
// SKIP: SIGWINCH — host-dependent.
// SKIP: SIGIO — host-dependent.
// SKIP: SIGPOLL — host-dependent.
// SKIP: SIGLOST — host-dependent.
// SKIP: SIGPWR — host-dependent.
// SKIP: SIGINFO — host-dependent.
// SKIP: SIGSYS — host-dependent.
// SKIP: SIGUNUSED — host-dependent.

// ── POSIX Error Constants (`os.constants.errno`) ──
// SKIP: E2BIG — host-dependent numeric value.
// SKIP: EACCES — host-dependent.
// SKIP: EADDRINUSE — host-dependent.
// SKIP: EADDRNOTAVAIL — host-dependent.
// SKIP: EAFNOSUPPORT — host-dependent.
// SKIP: EAGAIN — host-dependent.
// SKIP: EALREADY — host-dependent.
// SKIP: EBADF — host-dependent.
// SKIP: EBADMSG — host-dependent.
// SKIP: EBUSY — host-dependent.
// SKIP: ECANCELED — host-dependent.
// SKIP: ECHILD — host-dependent.
// SKIP: ECONNABORTED — host-dependent.
// SKIP: ECONNREFUSED — host-dependent.
// SKIP: ECONNRESET — host-dependent.
// SKIP: EDEADLK — host-dependent.
// SKIP: EDESTADDRREQ — host-dependent.
// SKIP: EDOM — host-dependent.
// SKIP: EDQUOT — host-dependent.
// SKIP: EEXIST — host-dependent.
// SKIP: EFAULT — host-dependent.
// SKIP: EFBIG — host-dependent.
// SKIP: EHOSTUNREACH — host-dependent.
// SKIP: EIDRM — host-dependent.
// SKIP: EILSEQ — host-dependent.
// SKIP: EINPROGRESS — host-dependent.
// SKIP: EINTR — host-dependent.
// SKIP: EINVAL — host-dependent.
// SKIP: EIO — host-dependent.
// SKIP: EISCONN — host-dependent.
// SKIP: EISDIR — host-dependent.
// SKIP: ELOOP — host-dependent.
// SKIP: EMFILE — host-dependent.
// SKIP: EMLINK — host-dependent.
// SKIP: EMSGSIZE — host-dependent.
// SKIP: EMULTIHOP — host-dependent.
// SKIP: ENAMETOOLONG — host-dependent.
// SKIP: ENETDOWN — host-dependent.
// SKIP: ENETRESET — host-dependent.
// SKIP: ENETUNREACH — host-dependent.
// SKIP: ENFILE — host-dependent.
// SKIP: ENOBUFS — host-dependent.
// SKIP: ENODATA — host-dependent.
// SKIP: ENODEV — host-dependent.
try { console.log("ENOENT:", os.constants.errno.ENOENT); } catch (e) { console.log("ENOENT threw"); }
// SKIP: ENOEXEC — host-dependent.
// SKIP: ENOLCK — host-dependent.
// SKIP: ENOLINK — host-dependent.
// SKIP: ENOMEM — host-dependent.
// SKIP: ENOMSG — host-dependent.
// SKIP: ENOPROTOOPT — host-dependent.
// SKIP: ENOSPC — host-dependent.
// SKIP: ENOSR — host-dependent.
// SKIP: ENOSTR — host-dependent.
// SKIP: ENOSYS — host-dependent.
// SKIP: ENOTCONN — host-dependent.
// SKIP: ENOTDIR — host-dependent.
// SKIP: ENOTEMPTY — host-dependent.
// SKIP: ENOTSOCK — host-dependent.
// SKIP: ENOTSUP — host-dependent.
// SKIP: ENOTTY — host-dependent.
// SKIP: ENXIO — host-dependent.
// SKIP: EOPNOTSUPP — host-dependent.
// SKIP: EOVERFLOW — host-dependent.
// SKIP: EPERM — host-dependent.
// SKIP: EPIPE — host-dependent.
// SKIP: EPROTO — host-dependent.
// SKIP: EPROTONOSUPPORT — host-dependent.
// SKIP: EPROTOTYPE — host-dependent.
// SKIP: ERANGE — host-dependent.
// SKIP: EROFS — host-dependent.
// SKIP: ESPIPE — host-dependent.
// SKIP: ESRCH — host-dependent.
// SKIP: ESTALE — host-dependent.
// SKIP: ETIME — host-dependent.
// SKIP: ETIMEDOUT — host-dependent.
// SKIP: ETXTBSY — host-dependent.
// SKIP: EWOULDBLOCK — host-dependent.
// SKIP: EXDEV — host-dependent.

// ── Windows-specific Error Constants (`os.constants.errno`) ──
// SKIP: WSAEINTR — Windows-only.
// SKIP: WSAEBADF — Windows-only.
// SKIP: WSAEACCES — Windows-only.
// SKIP: WSAEFAULT — Windows-only.
// SKIP: WSAEINVAL — Windows-only.
// SKIP: WSAEMFILE — Windows-only.
// SKIP: WSAEWOULDBLOCK — Windows-only.
// SKIP: WSAEINPROGRESS — Windows-only.
// SKIP: WSAEALREADY — Windows-only.
// SKIP: WSAENOTSOCK — Windows-only.
// SKIP: WSAEDESTADDRREQ — Windows-only.
// SKIP: WSAEMSGSIZE — Windows-only.
// SKIP: WSAEPROTOTYPE — Windows-only.
// SKIP: WSAENOPROTOOPT — Windows-only.
// SKIP: WSAEPROTONOSUPPORT — Windows-only.
// SKIP: WSAESOCKTNOSUPPORT — Windows-only.
// SKIP: WSAEOPNOTSUPP — Windows-only.
// SKIP: WSAEPFNOSUPPORT — Windows-only.
// SKIP: WSAEAFNOSUPPORT — Windows-only.
// SKIP: WSAEADDRINUSE — Windows-only.
// SKIP: WSAEADDRNOTAVAIL — Windows-only.
// SKIP: WSAENETDOWN — Windows-only.
// SKIP: WSAENETUNREACH — Windows-only.
// SKIP: WSAENETRESET — Windows-only.
// SKIP: WSAECONNABORTED — Windows-only.
// SKIP: WSAECONNRESET — Windows-only.
// SKIP: WSAENOBUFS — Windows-only.
// SKIP: WSAEISCONN — Windows-only.
// SKIP: WSAENOTCONN — Windows-only.
// SKIP: WSAESHUTDOWN — Windows-only.
// SKIP: WSAETOOMANYREFS — Windows-only.
// SKIP: WSAETIMEDOUT — Windows-only.
// SKIP: WSAECONNREFUSED — Windows-only.
// SKIP: WSAELOOP — Windows-only.
// SKIP: WSAENAMETOOLONG — Windows-only.
// SKIP: WSAEHOSTDOWN — Windows-only.
// SKIP: WSAEHOSTUNREACH — Windows-only.
// SKIP: WSAENOTEMPTY — Windows-only.
// SKIP: WSAEPROCLIM — Windows-only.
// SKIP: WSAEUSERS — Windows-only.
// SKIP: WSAEDQUOT — Windows-only.
// SKIP: WSAESTALE — Windows-only.
// SKIP: WSAEREMOTE — Windows-only.
// SKIP: WSASYSNOTREADY — Windows-only.
// SKIP: WSAVERNOTSUPPORTED — Windows-only.
// SKIP: WSANOTINITIALISED — Windows-only.
// SKIP: WSAEDISCON — Windows-only.
// SKIP: WSAENOMORE — Windows-only.
// SKIP: WSAECANCELLED — Windows-only.
// SKIP: WSAEINVALIDPROCTABLE — Windows-only.
// SKIP: WSAEINVALIDPROVIDER — Windows-only.
// SKIP: WSAEPROVIDERFAILEDINIT — Windows-only.
// SKIP: WSASYSCALLFAILURE — Windows-only.
// SKIP: WSASERVICE_NOT_FOUND — Windows-only.
// SKIP: WSATYPE_NOT_FOUND — Windows-only.
// SKIP: WSA_E_NO_MORE — Windows-only.
// SKIP: WSA_E_CANCELLED — Windows-only.
// SKIP: WSAEREFUSED — Windows-only.

// ── Priority Constants (`os.constants.priority`) ──
// SKIP: PRIORITY_LOW — host-dependent numeric value.
// SKIP: PRIORITY_BELOW_NORMAL — host-dependent numeric value.
try { console.log("PRIORITY_NORMAL:", os.constants.priority.PRIORITY_NORMAL); } catch (e) { console.log("PRIORITY_NORMAL threw"); }
// SKIP: PRIORITY_ABOVE_NORMAL — host-dependent numeric value.
// SKIP: PRIORITY_HIGH — host-dependent numeric value.
// SKIP: PRIORITY_HIGHEST — host-dependent numeric value.

// ── dlopen Constants (`os.constants.dlopen`) ──
try { console.log("RTLD_LAZY:", os.constants.dlopen.RTLD_LAZY); } catch (e) { console.log("RTLD_LAZY threw"); }
// SKIP: RTLD_NOW — host-dependent numeric value.
// SKIP: RTLD_GLOBAL — host-dependent numeric value.
// SKIP: RTLD_LOCAL — host-dependent numeric value.
// SKIP: RTLD_DEEPBIND — Linux-only.

// ── libuv Constants ──
console.log("os.constants.UV_UDP_REUSEADDR:", os.constants.UV_UDP_REUSEADDR);

// Coverage: 11 auto-emitted, 187 TODO, 11 skip-listed.
