// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:async_hooks
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_async_hooks` to verify.

import * as async_hooks from "node:async_hooks";


// ── Functions ──
try {
  console.log("async_hooks.executionAsyncId() typeof:", typeof async_hooks.executionAsyncId());
} catch (e: any) { console.log("executionAsyncId ERR:", e && e.message); }

try {
  console.log("async_hooks.triggerAsyncId() typeof:", typeof async_hooks.triggerAsyncId());
} catch (e: any) { console.log("triggerAsyncId ERR:", e && e.message); }

// PERRY-SKIP: async_hooks.executionAsyncResource() — return shape varies across runtimes.

// ── createHook ──
try {
  const hook = async_hooks.createHook({
    init() {},
    before() {},
    after() {},
    destroy() {},
    promiseResolve() {},
  });
  console.log("createHook typeof:", typeof hook);
  console.log("createHook.enable typeof:", typeof hook.enable);
  console.log("createHook.disable typeof:", typeof hook.disable);
  hook.enable();
  console.log("hook enabled OK");
  hook.disable();
  console.log("hook disabled OK");
} catch (e: any) { console.log("createHook ERR:", e && e.message); }

// PERRY-SKIP: async_hooks.asyncWrapProviders — bag of internal constants; host-dependent shape.

// ── Class: AsyncResource ──
try {
  const ar = new async_hooks.AsyncResource("MyResource");
  console.log("AsyncResource typeof:", typeof ar);
  console.log("AsyncResource.asyncId typeof:", typeof ar.asyncId());
  console.log("AsyncResource.triggerAsyncId typeof:", typeof ar.triggerAsyncId());
  const result = ar.runInAsyncScope(() => 42, null);
  console.log("AsyncResource.runInAsyncScope result:", result);
  ar.emitDestroy();
  console.log("AsyncResource.emitDestroy OK");
} catch (e: any) { console.log("AsyncResource ERR:", e && e.message); }

// PERRY-SKIP: AsyncResource.bind / static AsyncResource.bind — newer API surface, not exercised here.

// ── Class: AsyncLocalStorage ──
try {
  const als = new async_hooks.AsyncLocalStorage();
  console.log("AsyncLocalStorage typeof:", typeof als);
  console.log("AsyncLocalStorage.getStore (outside run):", als.getStore());
  const ran = als.run({ user: "alice" }, () => {
    const store: any = als.getStore();
    return store && store.user;
  });
  console.log("AsyncLocalStorage.run inner store user:", ran);
  console.log("AsyncLocalStorage.getStore (after run):", als.getStore());
  const exited = als.run({ user: "bob" }, () => {
    return als.exit(() => {
      return als.getStore();
    });
  });
  console.log("AsyncLocalStorage.exit returned:", exited);
  als.disable();
  console.log("AsyncLocalStorage.disable OK");
} catch (e: any) { console.log("AsyncLocalStorage ERR:", e && e.message); }

// PERRY-SKIP: AsyncLocalStorage.enterWith / bind / snapshot / static bind+snapshot — newer surface, omitted for determinism.

// Coverage: 4 auto-emitted, 25 TODO, 0 skip-listed.
