// #10476: a user method whose NAME matches a Date / Number / Array / String
// built-in must run on a receiver that is not that built-in. Pre-fix such a
// call was lowered to the built-in by name alone (NaN, "[object Object]",
// "Invalid time value", or a compile error for a zero-argument
// `endsWith`/`includes`/`startsWith`). This file covers class receivers: a
// class declares every name, directly and via `this`, typed and through `any`,
// plus `extends Date` subclasses with and without overrides. The sibling
// test_gap_10476_builtin_named_guarded_receivers.ts covers prototypes, object
// literals and `any` receivers in a module with no such class.
// Generated by a one-off script: one call site per (form, name, arity).

const cmp = (a: number, b: number) => b - a;
const add = (acc: number, v: number) => acc + v;
const dup = (v: number) => [v, v];

function tag(form: string, name: string, args: any[]): string {
  return form + "." + name + "/" + args.length;
}

function show(v: any): string {
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return "[" + v.join(",") + "]";
  return v === null ? "null" : typeof v;
}

// Error messages for a missing method differ between engines; the name is
// what matters here.
function attempt(f: () => any): string {
  try {
    return show(f());
  } catch (e) {
    return "THREW " + (e as Error).name;
  }
}

function attemptMessage(f: () => any): string {
  try {
    return show(f());
  } catch (e) {
    return "THREW " + String(e);
  }
}

function row(label: string, ...fs: Array<() => any>): void {
  console.log(label, fs.map(attempt).join(" "));
}

function viaAny(x: any, id: number): any {
  switch (id) {
    case 0: return x.getDate();
    case 1: return x.getDay();
    case 2: return x.getFullYear();
    case 3: return x.getHours();
    case 4: return x.getMilliseconds();
    case 5: return x.getMinutes();
    case 6: return x.getMonth();
    case 7: return x.getSeconds();
    case 8: return x.getTime();
    case 9: return x.getTimezoneOffset();
    case 10: return x.getUTCDate();
    case 11: return x.getUTCDay();
    case 12: return x.getUTCFullYear();
    case 13: return x.getUTCHours();
    case 14: return x.getUTCMilliseconds();
    case 15: return x.getUTCMinutes();
    case 16: return x.getUTCMonth();
    case 17: return x.getUTCSeconds();
    case 18: return x.setDate(1);
    case 19: return x.setFullYear(1);
    case 20: return x.setHours(1);
    case 21: return x.setMilliseconds(1);
    case 22: return x.setMinutes(1);
    case 23: return x.setMonth(1);
    case 24: return x.setSeconds(1);
    case 25: return x.setTime(1);
    case 26: return x.setUTCDate(1);
    case 27: return x.setUTCFullYear(1);
    case 28: return x.setUTCHours(1);
    case 29: return x.setUTCMilliseconds(1);
    case 30: return x.setUTCMinutes(1);
    case 31: return x.setUTCMonth(1);
    case 32: return x.setUTCSeconds(1);
    case 33: return x.toISOString();
    case 34: return x.toDateString();
    case 35: return x.toTimeString();
    case 36: return x.toUTCString();
    case 37: return x.toGMTString();
    case 38: return x.toLocaleString();
    case 39: return x.toLocaleDateString();
    case 40: return x.toLocaleTimeString();
    case 41: return x.toFixed(2);
    case 42: return x.toPrecision(2);
    case 43: return x.toExponential(2);
    case 44: return x.toFixed();
    case 45: return x.toSorted();
    case 46: return x.toSorted(cmp);
    case 47: return x.toReversed();
    case 48: return x.reduceRight(add);
    case 49: return x.flat();
    case 50: return x.flatMap(dup);
    case 51: return x.toSpliced(1);
    case 52: return x.toSpliced(0, 1);
    case 53: return x.copyWithin(0, 1);
    case 54: return x.endsWith();
    case 55: return x.includes();
    case 56: return x.startsWith();
    case 57: return x.endsWith('c');
    case 58: return x.includes('b');
    case 59: return x.startsWith('a');
  }
}

class K {
  getDate(...a: any[]): any { return tag("K", "getDate", a); }
  getDay(...a: any[]): any { return tag("K", "getDay", a); }
  getFullYear(...a: any[]): any { return tag("K", "getFullYear", a); }
  getHours(...a: any[]): any { return tag("K", "getHours", a); }
  getMilliseconds(...a: any[]): any { return tag("K", "getMilliseconds", a); }
  getMinutes(...a: any[]): any { return tag("K", "getMinutes", a); }
  getMonth(...a: any[]): any { return tag("K", "getMonth", a); }
  getSeconds(...a: any[]): any { return tag("K", "getSeconds", a); }
  getTime(...a: any[]): any { return tag("K", "getTime", a); }
  getTimezoneOffset(...a: any[]): any { return tag("K", "getTimezoneOffset", a); }
  getUTCDate(...a: any[]): any { return tag("K", "getUTCDate", a); }
  getUTCDay(...a: any[]): any { return tag("K", "getUTCDay", a); }
  getUTCFullYear(...a: any[]): any { return tag("K", "getUTCFullYear", a); }
  getUTCHours(...a: any[]): any { return tag("K", "getUTCHours", a); }
  getUTCMilliseconds(...a: any[]): any { return tag("K", "getUTCMilliseconds", a); }
  getUTCMinutes(...a: any[]): any { return tag("K", "getUTCMinutes", a); }
  getUTCMonth(...a: any[]): any { return tag("K", "getUTCMonth", a); }
  getUTCSeconds(...a: any[]): any { return tag("K", "getUTCSeconds", a); }
  setDate(...a: any[]): any { return tag("K", "setDate", a); }
  setFullYear(...a: any[]): any { return tag("K", "setFullYear", a); }
  setHours(...a: any[]): any { return tag("K", "setHours", a); }
  setMilliseconds(...a: any[]): any { return tag("K", "setMilliseconds", a); }
  setMinutes(...a: any[]): any { return tag("K", "setMinutes", a); }
  setMonth(...a: any[]): any { return tag("K", "setMonth", a); }
  setSeconds(...a: any[]): any { return tag("K", "setSeconds", a); }
  setTime(...a: any[]): any { return tag("K", "setTime", a); }
  setUTCDate(...a: any[]): any { return tag("K", "setUTCDate", a); }
  setUTCFullYear(...a: any[]): any { return tag("K", "setUTCFullYear", a); }
  setUTCHours(...a: any[]): any { return tag("K", "setUTCHours", a); }
  setUTCMilliseconds(...a: any[]): any { return tag("K", "setUTCMilliseconds", a); }
  setUTCMinutes(...a: any[]): any { return tag("K", "setUTCMinutes", a); }
  setUTCMonth(...a: any[]): any { return tag("K", "setUTCMonth", a); }
  setUTCSeconds(...a: any[]): any { return tag("K", "setUTCSeconds", a); }
  toISOString(...a: any[]): any { return tag("K", "toISOString", a); }
  toDateString(...a: any[]): any { return tag("K", "toDateString", a); }
  toTimeString(...a: any[]): any { return tag("K", "toTimeString", a); }
  toUTCString(...a: any[]): any { return tag("K", "toUTCString", a); }
  toGMTString(...a: any[]): any { return tag("K", "toGMTString", a); }
  toLocaleString(...a: any[]): any { return tag("K", "toLocaleString", a); }
  toLocaleDateString(...a: any[]): any { return tag("K", "toLocaleDateString", a); }
  toLocaleTimeString(...a: any[]): any { return tag("K", "toLocaleTimeString", a); }
  toFixed(...a: any[]): any { return tag("K", "toFixed", a); }
  toPrecision(...a: any[]): any { return tag("K", "toPrecision", a); }
  toExponential(...a: any[]): any { return tag("K", "toExponential", a); }
  toSorted(...a: any[]): any { return tag("K", "toSorted", a); }
  toReversed(...a: any[]): any { return tag("K", "toReversed", a); }
  reduceRight(...a: any[]): any { return tag("K", "reduceRight", a); }
  flat(...a: any[]): any { return tag("K", "flat", a); }
  flatMap(...a: any[]): any { return tag("K", "flatMap", a); }
  toSpliced(...a: any[]): any { return tag("K", "toSpliced", a); }
  copyWithin(...a: any[]): any { return tag("K", "copyWithin", a); }
  endsWith(...a: any[]): any { return tag("K", "endsWith", a); }
  includes(...a: any[]): any { return tag("K", "includes", a); }
  startsWith(...a: any[]): any { return tag("K", "startsWith", a); }
  viaThis(id: number): any {
    switch (id) {
      case 0: return this.getDate();
      case 1: return this.getDay();
      case 2: return this.getFullYear();
      case 3: return this.getHours();
      case 4: return this.getMilliseconds();
      case 5: return this.getMinutes();
      case 6: return this.getMonth();
      case 7: return this.getSeconds();
      case 8: return this.getTime();
      case 9: return this.getTimezoneOffset();
      case 10: return this.getUTCDate();
      case 11: return this.getUTCDay();
      case 12: return this.getUTCFullYear();
      case 13: return this.getUTCHours();
      case 14: return this.getUTCMilliseconds();
      case 15: return this.getUTCMinutes();
      case 16: return this.getUTCMonth();
      case 17: return this.getUTCSeconds();
      case 18: return this.setDate(1);
      case 19: return this.setFullYear(1);
      case 20: return this.setHours(1);
      case 21: return this.setMilliseconds(1);
      case 22: return this.setMinutes(1);
      case 23: return this.setMonth(1);
      case 24: return this.setSeconds(1);
      case 25: return this.setTime(1);
      case 26: return this.setUTCDate(1);
      case 27: return this.setUTCFullYear(1);
      case 28: return this.setUTCHours(1);
      case 29: return this.setUTCMilliseconds(1);
      case 30: return this.setUTCMinutes(1);
      case 31: return this.setUTCMonth(1);
      case 32: return this.setUTCSeconds(1);
      case 33: return this.toISOString();
      case 34: return this.toDateString();
      case 35: return this.toTimeString();
      case 36: return this.toUTCString();
      case 37: return this.toGMTString();
      case 38: return this.toLocaleString();
      case 39: return this.toLocaleDateString();
      case 40: return this.toLocaleTimeString();
      case 41: return this.toFixed(2);
      case 42: return this.toPrecision(2);
      case 43: return this.toExponential(2);
      case 44: return this.toFixed();
      case 45: return this.toSorted();
      case 46: return this.toSorted(cmp);
      case 47: return this.toReversed();
      case 48: return this.reduceRight(add);
      case 49: return this.flat();
      case 50: return this.flatMap(dup);
      case 51: return this.toSpliced(1);
      case 52: return this.toSpliced(0, 1);
      case 53: return this.copyWithin(0, 1);
      case 54: return this.endsWith();
      case 55: return this.includes();
      case 56: return this.startsWith();
      case 57: return this.endsWith('c');
      case 58: return this.includes('b');
      case 59: return this.startsWith('a');
    }
  }
}

class Sub extends K {}

const k = new K();
const sub = new Sub();
const kAny: any = new K();

row("getDate()", () => k.getDate(), () => k.viaThis(0), () => sub.getDate(), () => kAny.getDate(), () => viaAny(k, 0));
row("getDay()", () => k.getDay(), () => k.viaThis(1), () => sub.getDay(), () => kAny.getDay(), () => viaAny(k, 1));
row("getFullYear()", () => k.getFullYear(), () => k.viaThis(2), () => sub.getFullYear(), () => kAny.getFullYear(), () => viaAny(k, 2));
row("getHours()", () => k.getHours(), () => k.viaThis(3), () => sub.getHours(), () => kAny.getHours(), () => viaAny(k, 3));
row("getMilliseconds()", () => k.getMilliseconds(), () => k.viaThis(4), () => sub.getMilliseconds(), () => kAny.getMilliseconds(), () => viaAny(k, 4));
row("getMinutes()", () => k.getMinutes(), () => k.viaThis(5), () => sub.getMinutes(), () => kAny.getMinutes(), () => viaAny(k, 5));
row("getMonth()", () => k.getMonth(), () => k.viaThis(6), () => sub.getMonth(), () => kAny.getMonth(), () => viaAny(k, 6));
row("getSeconds()", () => k.getSeconds(), () => k.viaThis(7), () => sub.getSeconds(), () => kAny.getSeconds(), () => viaAny(k, 7));
row("getTime()", () => k.getTime(), () => k.viaThis(8), () => sub.getTime(), () => kAny.getTime(), () => viaAny(k, 8));
row("getTimezoneOffset()", () => k.getTimezoneOffset(), () => k.viaThis(9), () => sub.getTimezoneOffset(), () => kAny.getTimezoneOffset(), () => viaAny(k, 9));
row("getUTCDate()", () => k.getUTCDate(), () => k.viaThis(10), () => sub.getUTCDate(), () => kAny.getUTCDate(), () => viaAny(k, 10));
row("getUTCDay()", () => k.getUTCDay(), () => k.viaThis(11), () => sub.getUTCDay(), () => kAny.getUTCDay(), () => viaAny(k, 11));
row("getUTCFullYear()", () => k.getUTCFullYear(), () => k.viaThis(12), () => sub.getUTCFullYear(), () => kAny.getUTCFullYear(), () => viaAny(k, 12));
row("getUTCHours()", () => k.getUTCHours(), () => k.viaThis(13), () => sub.getUTCHours(), () => kAny.getUTCHours(), () => viaAny(k, 13));
row("getUTCMilliseconds()", () => k.getUTCMilliseconds(), () => k.viaThis(14), () => sub.getUTCMilliseconds(), () => kAny.getUTCMilliseconds(), () => viaAny(k, 14));
row("getUTCMinutes()", () => k.getUTCMinutes(), () => k.viaThis(15), () => sub.getUTCMinutes(), () => kAny.getUTCMinutes(), () => viaAny(k, 15));
row("getUTCMonth()", () => k.getUTCMonth(), () => k.viaThis(16), () => sub.getUTCMonth(), () => kAny.getUTCMonth(), () => viaAny(k, 16));
row("getUTCSeconds()", () => k.getUTCSeconds(), () => k.viaThis(17), () => sub.getUTCSeconds(), () => kAny.getUTCSeconds(), () => viaAny(k, 17));
row("setDate(1)", () => k.setDate(1), () => k.viaThis(18), () => sub.setDate(1), () => kAny.setDate(1), () => viaAny(k, 18));
row("setFullYear(1)", () => k.setFullYear(1), () => k.viaThis(19), () => sub.setFullYear(1), () => kAny.setFullYear(1), () => viaAny(k, 19));
row("setHours(1)", () => k.setHours(1), () => k.viaThis(20), () => sub.setHours(1), () => kAny.setHours(1), () => viaAny(k, 20));
row("setMilliseconds(1)", () => k.setMilliseconds(1), () => k.viaThis(21), () => sub.setMilliseconds(1), () => kAny.setMilliseconds(1), () => viaAny(k, 21));
row("setMinutes(1)", () => k.setMinutes(1), () => k.viaThis(22), () => sub.setMinutes(1), () => kAny.setMinutes(1), () => viaAny(k, 22));
row("setMonth(1)", () => k.setMonth(1), () => k.viaThis(23), () => sub.setMonth(1), () => kAny.setMonth(1), () => viaAny(k, 23));
row("setSeconds(1)", () => k.setSeconds(1), () => k.viaThis(24), () => sub.setSeconds(1), () => kAny.setSeconds(1), () => viaAny(k, 24));
row("setTime(1)", () => k.setTime(1), () => k.viaThis(25), () => sub.setTime(1), () => kAny.setTime(1), () => viaAny(k, 25));
row("setUTCDate(1)", () => k.setUTCDate(1), () => k.viaThis(26), () => sub.setUTCDate(1), () => kAny.setUTCDate(1), () => viaAny(k, 26));
row("setUTCFullYear(1)", () => k.setUTCFullYear(1), () => k.viaThis(27), () => sub.setUTCFullYear(1), () => kAny.setUTCFullYear(1), () => viaAny(k, 27));
row("setUTCHours(1)", () => k.setUTCHours(1), () => k.viaThis(28), () => sub.setUTCHours(1), () => kAny.setUTCHours(1), () => viaAny(k, 28));
row("setUTCMilliseconds(1)", () => k.setUTCMilliseconds(1), () => k.viaThis(29), () => sub.setUTCMilliseconds(1), () => kAny.setUTCMilliseconds(1), () => viaAny(k, 29));
row("setUTCMinutes(1)", () => k.setUTCMinutes(1), () => k.viaThis(30), () => sub.setUTCMinutes(1), () => kAny.setUTCMinutes(1), () => viaAny(k, 30));
row("setUTCMonth(1)", () => k.setUTCMonth(1), () => k.viaThis(31), () => sub.setUTCMonth(1), () => kAny.setUTCMonth(1), () => viaAny(k, 31));
row("setUTCSeconds(1)", () => k.setUTCSeconds(1), () => k.viaThis(32), () => sub.setUTCSeconds(1), () => kAny.setUTCSeconds(1), () => viaAny(k, 32));
row("toISOString()", () => k.toISOString(), () => k.viaThis(33), () => sub.toISOString(), () => kAny.toISOString(), () => viaAny(k, 33));
row("toDateString()", () => k.toDateString(), () => k.viaThis(34), () => sub.toDateString(), () => kAny.toDateString(), () => viaAny(k, 34));
row("toTimeString()", () => k.toTimeString(), () => k.viaThis(35), () => sub.toTimeString(), () => kAny.toTimeString(), () => viaAny(k, 35));
row("toUTCString()", () => k.toUTCString(), () => k.viaThis(36), () => sub.toUTCString(), () => kAny.toUTCString(), () => viaAny(k, 36));
row("toGMTString()", () => k.toGMTString(), () => k.viaThis(37), () => sub.toGMTString(), () => kAny.toGMTString(), () => viaAny(k, 37));
row("toLocaleString()", () => k.toLocaleString(), () => k.viaThis(38), () => sub.toLocaleString(), () => kAny.toLocaleString(), () => viaAny(k, 38));
row("toLocaleDateString()", () => k.toLocaleDateString(), () => k.viaThis(39), () => sub.toLocaleDateString(), () => kAny.toLocaleDateString(), () => viaAny(k, 39));
row("toLocaleTimeString()", () => k.toLocaleTimeString(), () => k.viaThis(40), () => sub.toLocaleTimeString(), () => kAny.toLocaleTimeString(), () => viaAny(k, 40));
row("toFixed(2)", () => k.toFixed(2), () => k.viaThis(41), () => sub.toFixed(2), () => kAny.toFixed(2), () => viaAny(k, 41));
row("toPrecision(2)", () => k.toPrecision(2), () => k.viaThis(42), () => sub.toPrecision(2), () => kAny.toPrecision(2), () => viaAny(k, 42));
row("toExponential(2)", () => k.toExponential(2), () => k.viaThis(43), () => sub.toExponential(2), () => kAny.toExponential(2), () => viaAny(k, 43));
row("toFixed()", () => k.toFixed(), () => k.viaThis(44), () => sub.toFixed(), () => kAny.toFixed(), () => viaAny(k, 44));
row("toSorted()", () => k.toSorted(), () => k.viaThis(45), () => sub.toSorted(), () => kAny.toSorted(), () => viaAny(k, 45));
row("toSorted(cmp)", () => k.toSorted(cmp), () => k.viaThis(46), () => sub.toSorted(cmp), () => kAny.toSorted(cmp), () => viaAny(k, 46));
row("toReversed()", () => k.toReversed(), () => k.viaThis(47), () => sub.toReversed(), () => kAny.toReversed(), () => viaAny(k, 47));
row("reduceRight(add)", () => k.reduceRight(add), () => k.viaThis(48), () => sub.reduceRight(add), () => kAny.reduceRight(add), () => viaAny(k, 48));
row("flat()", () => k.flat(), () => k.viaThis(49), () => sub.flat(), () => kAny.flat(), () => viaAny(k, 49));
row("flatMap(dup)", () => k.flatMap(dup), () => k.viaThis(50), () => sub.flatMap(dup), () => kAny.flatMap(dup), () => viaAny(k, 50));
row("toSpliced(1)", () => k.toSpliced(1), () => k.viaThis(51), () => sub.toSpliced(1), () => kAny.toSpliced(1), () => viaAny(k, 51));
row("toSpliced(0, 1)", () => k.toSpliced(0, 1), () => k.viaThis(52), () => sub.toSpliced(0, 1), () => kAny.toSpliced(0, 1), () => viaAny(k, 52));
row("copyWithin(0, 1)", () => k.copyWithin(0, 1), () => k.viaThis(53), () => sub.copyWithin(0, 1), () => kAny.copyWithin(0, 1), () => viaAny(k, 53));
row("endsWith()", () => k.endsWith(), () => k.viaThis(54), () => sub.endsWith(), () => kAny.endsWith(), () => viaAny(k, 54));
row("includes()", () => k.includes(), () => k.viaThis(55), () => sub.includes(), () => kAny.includes(), () => viaAny(k, 55));
row("startsWith()", () => k.startsWith(), () => k.viaThis(56), () => sub.startsWith(), () => kAny.startsWith(), () => viaAny(k, 56));
row("endsWith('c')", () => k.endsWith('c'), () => k.viaThis(57), () => sub.endsWith('c'), () => kAny.endsWith('c'), () => viaAny(k, 57));
row("includes('b')", () => k.includes('b'), () => k.viaThis(58), () => sub.includes('b'), () => kAny.includes('b'), () => viaAny(k, 58));
row("startsWith('a')", () => k.startsWith('a'), () => k.viaThis(59), () => sub.startsWith('a'), () => kAny.startsWith('a'), () => viaAny(k, 59));

// A Date subclass is a Date at runtime; its own overrides must still win.
class OverDate extends Date {
  getTime(): any { return "OverDate.getTime"; }
  toISOString(): any { return "OverDate.toISOString"; }
  setUTCHours(h: number): any { return "OverDate.setUTCHours/" + h; }
  toFixed(d: number): any { return "OverDate.toFixed/" + d; }
}
class PlainDate extends Date {}
const od = new OverDate(86400000);
const odAny: any = new OverDate(86400000);
const pd = new PlainDate(86400000);
const pdAny: any = new PlainDate(86400000);
row("OverDate", () => od.getTime(), () => od.toISOString(), () => od.setUTCHours(3), () => od.getUTCDate(), () => od.toFixed(1));
row("OverDate any", () => odAny.getTime(), () => odAny.toISOString(), () => odAny.setUTCHours(3), () => odAny.getUTCDate());
row("PlainDate", () => pd.getTime(), () => pd.toISOString(), () => pd.getUTCDate(), () => pdAny.getTime(), () => pdAny.toISOString(), () => viaAny(pdAny, 33));

// Real built-ins through `any` in a module whose classes declare the names.
const du: any = new Date(Date.UTC(2024, 5, 15, 10, 20, 30, 456));
const nu: any = 1234.5678;
const au: any = [5, 4, 6];
const su: any = "xundefined";
row("builtins any", () => du.getTime(), () => du.toISOString(), () => du.getUTCHours(), () => nu.toFixed(2), () => nu.toPrecision(3), () => au.toSorted(), () => au.toReversed(), () => au.reduceRight(add), () => su.endsWith(), () => su.includes("und"));
{ const t: any = new Date(0); row("builtins any setter", () => t.setUTCHours(5), () => t.toISOString(), () => viaAny(t, 30)); }
// One call site per name, the matching built-in and class instances in turn.
for (const m of [new Date(0), k, sub] as any[]) row("mixed getTime", () => viaAny(m, 8));
for (const m of [pd, k, sub] as any[]) row("mixed toISOString", () => viaAny(m, 33));
for (const m of [7, k, sub] as any[]) row("mixed toFixed", () => viaAny(m, 41));
for (const m of [[3, 1, 2], k, sub] as any[]) row("mixed toSorted", () => viaAny(m, 45));
for (const m of ["xundefined", k, sub] as any[]) row("mixed endsWith", () => viaAny(m, 54));
