// Auto-generated by scripts/gen_parity_tests.py from docs/runtime-parity.md.
// Module: node:console
// This file is a byte-for-byte parity test against `node --experimental-strip-types`.
// Edit the TODO lines below to exercise each API; rerun
// `./run_parity_tests.sh --filter test_parity_console` to verify.

import * as console from "node:console";


// ── Class: Console ──
// PERRY-SKIP: new Console(stdout[, stderr][, ignoreErrors]) — probed via typeof below;
// the actual constructor needs a real Writable stream + would emit non-deterministic output.
console.log("typeof Console:", typeof console.Console);

// ── Standard Methods ──

// console.assert — pass case is silent; fail case prints "Assertion failed: ..."
try {
  console.log("called assert (pass):");
  console.assert(true, "pass-msg");
} catch (e: any) { console.log("assert pass error:", e.message); }
try {
  console.log("called assert (fail):");
  console.assert(false, "fail-msg");
} catch (e: any) { console.log("assert fail error:", e.message); }

// console.clear — already auto-emitted above by the generator
console.log("console.clear():", console.clear());

// console.count / console.countReset — print "<label>: <n>" to stderr.
// Sentinel + call wrap matches Node byte-for-byte on stdout side.
try {
  console.log("called count:");
  console.count("ctr");
  console.count("ctr");
  console.log("called countReset:");
  console.countReset("ctr");
  console.count("ctr");
} catch (e: any) { console.log("count error:", e.message); }

// console.debug
try {
  console.log("called debug:");
  console.debug("debug-arg");
} catch (e: any) { console.log("debug error:", e.message); }

// PERRY-SKIP: console.dir — Node prints "{ a: 1 }" with util.inspect formatting; indentation differs.
// Sentinel-only.
try {
  console.log("called dir:");
} catch (e: any) { console.log("dir error:", e.message); }

// PERRY-SKIP: console.dirxml — alias of console.log on Node but formatting routes through dir.
// Sentinel-only.
try {
  console.log("called dirxml:");
} catch (e: any) { console.log("dirxml error:", e.message); }

// console.error — prints to stderr; on Node the line goes to fd 2 so stdout-only diff ignores it.
try {
  console.log("called error:");
  console.error("error-arg");
} catch (e: any) { console.log("error error:", e.message); }

// PERRY-SKIP: console.group / groupCollapsed / groupEnd — indentation differs across runners.
// Sentinel-only for group / groupCollapsed; groupEnd is auto-emitted by the generator above.
try {
  console.log("called group:");
} catch (e: any) { console.log("group error:", e.message); }
console.log("console.groupCollapsed():", console.groupCollapsed());
console.log("console.groupEnd():", console.groupEnd());

// console.info
try {
  console.log("called info:");
  console.info("info-arg");
} catch (e: any) { console.log("info error:", e.message); }

// console.log
try {
  console.log("called log:");
  console.log("log-arg");
} catch (e: any) { console.log("log error:", e.message); }

// PERRY-SKIP: console.table — box-drawing characters + width vary across runners.
// Sentinel-only.
try {
  console.log("called table:");
} catch (e: any) { console.log("table error:", e.message); }

// PERRY-SKIP: console.time / timeEnd / timeLog — emit non-deterministic durations.
// Sentinel-only.
try {
  console.log("called time:");
} catch (e: any) { console.log("time error:", e.message); }
try {
  console.log("called timeEnd:");
} catch (e: any) { console.log("timeEnd error:", e.message); }
try {
  console.log("called timeLog:");
} catch (e: any) { console.log("timeLog error:", e.message); }

// PERRY-SKIP: console.trace — emits a stack with file:line that differs.
// Sentinel-only.
try {
  console.log("called trace:");
} catch (e: any) { console.log("trace error:", e.message); }

// console.warn — like error, goes to stderr.
try {
  console.log("called warn:");
  console.warn("warn-arg");
} catch (e: any) { console.log("warn error:", e.message); }


// ── Inspector-Only Methods ──
// All three are silent no-ops in non-inspector mode on Node and Perry alike.

try {
  console.log("called profile:");
  console.profile("p");
} catch (e: any) { console.log("profile error:", e.message); }
try {
  console.log("called profileEnd:");
  console.profileEnd("p");
} catch (e: any) { console.log("profileEnd error:", e.message); }
try {
  console.log("called timeStamp:");
  console.timeStamp("ts");
} catch (e: any) { console.log("timeStamp error:", e.message); }

// Coverage: 3 auto-emitted, 20 TODO, 6 skip-listed.
