use super::super::*;
use super::*;

pub(crate) const NODE_CORE_ASSERT_ROWS: &[NativeModSig] = &[
    // ========== Node assert ==========
    // Root-callable `assert(value, message?)` — HIR lowers
    // `import assert from "node:assert"; assert(x, m)` to a
    // `NativeMethodCall { module: "assert", method: "default" }`.
    // Route it to `js_assert_ok` (Node's default export aliases
    // `assert.ok`). Same for `node:assert/strict`.
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // `assert.strict(value, msg?)` — the `.strict` namespace itself is
    // callable and behaves like `assert.strict.ok`.
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "strict",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "strict",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "ok",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "fail",
        class_filter: None,
        runtime: "js_assert_fail",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "equal",
        class_filter: None,
        runtime: "js_assert_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notEqual",
        class_filter: None,
        runtime: "js_assert_not_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "strictEqual",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "deepEqual",
        class_filter: None,
        runtime: "js_assert_deep_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notDeepEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "deepStrictEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "partialDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_partial_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "notDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "match",
        class_filter: None,
        runtime: "js_assert_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotMatch",
        class_filter: None,
        runtime: "js_assert_does_not_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "throws",
        class_filter: None,
        runtime: "js_assert_throws",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotThrow",
        class_filter: None,
        runtime: "js_assert_does_not_throw",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "rejects",
        class_filter: None,
        runtime: "js_assert_rejects",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "doesNotReject",
        class_filter: None,
        runtime: "js_assert_does_not_reject",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert",
        has_receiver: false,
        method: "ifError",
        class_filter: None,
        runtime: "js_assert_if_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "ok",
        class_filter: None,
        runtime: "js_assert_ok",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "fail",
        class_filter: None,
        runtime: "js_assert_fail",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "equal",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "deepEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notDeepEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "strictEqual",
        class_filter: None,
        runtime: "js_assert_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "deepStrictEqual",
        class_filter: None,
        runtime: "js_assert_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "partialDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_partial_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "notDeepStrictEqual",
        class_filter: None,
        runtime: "js_assert_not_deep_strict_equal",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "match",
        class_filter: None,
        runtime: "js_assert_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotMatch",
        class_filter: None,
        runtime: "js_assert_does_not_match",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "throws",
        class_filter: None,
        runtime: "js_assert_throws",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotThrow",
        class_filter: None,
        runtime: "js_assert_does_not_throw",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "rejects",
        class_filter: None,
        runtime: "js_assert_rejects",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "doesNotReject",
        class_filter: None,
        runtime: "js_assert_does_not_reject",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "assert/strict",
        has_receiver: false,
        method: "ifError",
        class_filter: None,
        runtime: "js_assert_if_error",
        args: &[NA_F64],
        ret: NR_F64,
    },
];
