use super::super::*;
use super::*;

pub(crate) const NODE_CORE_DGRAM_FS_OS_ROWS: &[NativeModSig] = &[
    // ========== Node dgram deterministic loopback subset ==========
    NativeModSig {
        module: "dgram",
        has_receiver: false,
        method: "createSocket",
        class_filter: None,
        runtime: "js_dgram_create_socket",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: false,
        method: "Socket",
        class_filter: None,
        runtime: "js_dgram_create_socket",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "send",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_send",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "bind",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_bind",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "close",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_close",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "address",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_address",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "remoteAddress",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_remote_address",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "connect",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_connect",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "disconnect",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_disconnect",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "on",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_on",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_on",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "once",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_once",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "off",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_remove_listener",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "removeListener",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_remove_listener",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "emit",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_emit",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "listenerCount",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_listener_count",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "eventNames",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_event_names",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "addMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_add_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "dropMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_drop_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "addSourceSpecificMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_add_source_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "dropSourceSpecificMembership",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_drop_source_membership",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setBroadcast",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_broadcast",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setMulticastTTL",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_multicast_ttl",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setMulticastLoopback",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_multicast_loopback",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setMulticastInterface",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_multicast_interface",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setTTL",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_ttl",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setRecvBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_recv_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "setSendBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_set_send_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getRecvBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_get_recv_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getSendBufferSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_get_send_buffer_size",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getSendQueueSize",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_zero",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "getSendQueueCount",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_zero",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "ref",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_ref",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dgram",
        has_receiver: true,
        method: "unref",
        class_filter: Some("Socket"),
        runtime: "js_dgram_socket_unref",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    // ========== Node FS ==========
    NativeModSig {
        module: "fs",
        has_receiver: false,
        method: "_toUnixTimestamp",
        class_filter: None,
        runtime: "js_fs_to_unix_timestamp",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node TTY ==========
    NativeModSig {
        module: "tty",
        has_receiver: false,
        method: "isatty",
        class_filter: None,
        runtime: "js_tty_isatty",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tty",
        has_receiver: false,
        method: "ReadStream",
        class_filter: None,
        runtime: "js_tty_read_stream_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "tty",
        has_receiver: false,
        method: "WriteStream",
        class_filter: None,
        runtime: "js_tty_write_stream_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node WASI ==========
    NativeModSig {
        module: "wasi",
        has_receiver: false,
        method: "WASI",
        class_filter: None,
        runtime: "js_wasi_constructor_call",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node OS ==========
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "getPriority",
        class_filter: None,
        runtime: "js_os_get_priority",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "setPriority",
        class_filter: None,
        runtime: "js_os_set_priority",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // #3004 — `os.userInfo(options)` with a dynamic options object (variable,
    // function return, computed-key). The runtime inspects `options.encoding`
    // and returns Buffer text fields only on an exact `"buffer"` match. The
    // static-literal `{ encoding: "buffer" }` form is lowered separately to
    // `OsUserInfoBuffer`; this table entry handles everything else.
    NativeModSig {
        module: "os",
        has_receiver: false,
        method: "userInfo",
        class_filter: None,
        runtime: "js_os_user_info_options",
        args: &[NA_JSV],
        ret: NR_PTR,
    },
];
