use super::super::*;
use super::*;

pub(crate) const NODE_CORE_INSPECTOR_VM_ROWS: &[NativeModSig] = &[
    // ========== Node inspector ==========
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "open",
        class_filter: None,
        runtime: "js_node_inspector_open",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "close",
        class_filter: None,
        runtime: "js_node_inspector_close",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "url",
        class_filter: None,
        runtime: "js_node_inspector_url",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "waitForDebugger",
        class_filter: None,
        runtime: "js_node_inspector_wait_for_debugger",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: false,
        method: "Session",
        class_filter: None,
        runtime: "js_node_inspector_session_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "requestWillBeSent",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "responseReceived",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "loadingFinished",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "loadingFailed",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "dataSent",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "dataReceived",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "webSocketCreated",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "webSocketClosed",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector.Network",
        has_receiver: false,
        method: "webSocketHandshakeResponseReceived",
        class_filter: None,
        runtime: "js_node_inspector_network_notify",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: false,
        method: "Session",
        class_filter: None,
        runtime: "js_node_inspector_promises_session_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "connect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "connectToMainThread",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect_to_main_thread",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "disconnect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_disconnect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "post",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_post",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "on",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_on",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector",
        has_receiver: true,
        method: "once",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_once",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "connect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "connectToMainThread",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_connect_to_main_thread",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "disconnect",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_disconnect",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "post",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_post",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "on",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_on",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "inspector/promises",
        has_receiver: true,
        method: "once",
        class_filter: Some("Session"),
        runtime: "js_node_inspector_session_once",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node vm scaffold ==========
    // `createContext` is intentionally omitted here: it is implemented on main
    // (#4050) via the node_submodules thunk + `object::js_vm_create_context`,
    // which returns a usable context object. The remaining surface is the
    // shape-only scaffold (#4079) plus measureMemory validation (#4087).
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "createScript",
        class_filter: None,
        runtime: "js_vm_create_script",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "runInContext",
        class_filter: None,
        runtime: "js_vm_run_in_context",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "runInNewContext",
        class_filter: None,
        runtime: "js_vm_run_in_new_context",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "runInThisContext",
        class_filter: None,
        runtime: "js_vm_run_in_this_context",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "isContext",
        class_filter: None,
        runtime: "js_vm_is_context",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "compileFunction",
        class_filter: None,
        runtime: "js_vm_compile_function",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "measureMemory",
        class_filter: None,
        runtime: "js_vm_measure_memory",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "Module",
        class_filter: None,
        runtime: "js_vm_module_call",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "SourceTextModule",
        class_filter: None,
        runtime: "js_vm_source_text_module_new",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "SyntheticModule",
        class_filter: None,
        runtime: "js_vm_synthetic_module_new",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "status",
        class_filter: None,
        runtime: "js_vm_module_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "identifier",
        class_filter: None,
        runtime: "js_vm_module_identifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "error",
        class_filter: None,
        runtime: "js_vm_module_error",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "namespace",
        class_filter: None,
        runtime: "js_vm_module_namespace",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "dependencySpecifiers",
        class_filter: None,
        runtime: "js_vm_source_text_module_dependency_specifiers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "moduleRequests",
        class_filter: None,
        runtime: "js_vm_source_text_module_module_requests",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "status",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "status",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "identifier",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_identifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "identifier",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_identifier",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "error",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_error",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "error",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_error",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "namespace",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_namespace",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "namespace",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_namespace",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "link",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_link",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "link",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_link",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "evaluate",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_module_evaluate",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "evaluate",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_module_evaluate",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "dependencySpecifiers",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_dependency_specifiers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "moduleRequests",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_module_requests",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "createCachedData",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_create_cached_data",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "linkRequests",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_link_requests",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "instantiate",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_instantiate",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "hasTopLevelAwait",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_has_top_level_await",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "hasAsyncGraph",
        class_filter: Some("SourceTextModule"),
        runtime: "js_vm_source_text_module_has_async_graph",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "vm",
        has_receiver: true,
        method: "setExport",
        class_filter: Some("SyntheticModule"),
        runtime: "js_vm_synthetic_module_set_export",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
];
