use super::super::*;
use super::*;

pub(crate) const NODE_CORE_URL_PUNYCODE_CONSOLE_ROWS: &[NativeModSig] = &[
    // ========== Node URL ==========
    // `new Number/String/Boolean(...)` now lowers to
    // `Expr::BoxedPrimitiveNew` (see crates/perry-hir/src/lower/expr_new.rs)
    // and is emitted by codegen as a direct runtime call — no dispatch
    // table row needed.
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "fileURLToPath",
        class_filter: None,
        runtime: "js_url_file_url_to_path",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "fileURLToPathBuffer",
        class_filter: None,
        runtime: "js_url_file_url_to_path_buffer",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "pathToFileURL",
        class_filter: None,
        runtime: "js_url_path_to_file_url",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "domainToASCII",
        class_filter: None,
        runtime: "js_url_domain_to_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "domainToUnicode",
        class_filter: None,
        runtime: "js_url_domain_to_unicode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "urlToHttpOptions",
        class_filter: None,
        runtime: "js_url_to_http_options",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "URLPattern",
        class_filter: None,
        runtime: "js_url_pattern_constructor_call",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: true,
        method: "exec",
        class_filter: Some("URLPattern"),
        runtime: "js_url_pattern_exec",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: true,
        method: "test",
        class_filter: Some("URLPattern"),
        runtime: "js_url_pattern_test",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "Url",
        class_filter: None,
        runtime: "js_url_legacy_url_new",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "format",
        class_filter: None,
        runtime: "js_url_format",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "parse",
        class_filter: None,
        runtime: "js_url_legacy_parse",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "resolve",
        class_filter: None,
        runtime: "js_url_legacy_resolve",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "url",
        has_receiver: false,
        method: "resolveObject",
        class_filter: None,
        runtime: "js_url_legacy_resolve_object",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== Node punycode (deprecated, #2513) ==========
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "decode",
        class_filter: None,
        runtime: "js_punycode_decode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "encode",
        class_filter: None,
        runtime: "js_punycode_encode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "toASCII",
        class_filter: None,
        runtime: "js_punycode_to_ascii",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode",
        has_receiver: false,
        method: "toUnicode",
        class_filter: None,
        runtime: "js_punycode_to_unicode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // punycode.ucs2 sub-namespace (#2607): decode(string)->code-point array,
    // encode(code-point array)->string. The array arg/return ride as a
    // NaN-boxed pointer in the NA_F64 slot.
    NativeModSig {
        module: "punycode.ucs2",
        has_receiver: false,
        method: "decode",
        class_filter: None,
        runtime: "js_punycode_ucs2_decode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "punycode.ucs2",
        has_receiver: false,
        method: "encode",
        class_filter: None,
        runtime: "js_punycode_ucs2_encode",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== Node console ==========
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "log",
        class_filter: None,
        runtime: "js_console_log_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "info",
        class_filter: None,
        runtime: "js_console_info_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "debug",
        class_filter: None,
        runtime: "js_console_debug_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "dirxml",
        class_filter: None,
        runtime: "js_console_log_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "error",
        class_filter: None,
        runtime: "js_console_error_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "warn",
        class_filter: None,
        runtime: "js_console_warn_spread",
        args: &[NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "assert",
        class_filter: None,
        runtime: "js_console_assert_spread",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "dir",
        class_filter: None,
        runtime: "js_console_log_dynamic",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "trace",
        class_filter: None,
        runtime: "js_console_trace",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "table",
        class_filter: None,
        runtime: "js_console_table",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "clear",
        class_filter: None,
        runtime: "js_console_clear",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "count",
        class_filter: None,
        runtime: "js_console_count",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "countReset",
        class_filter: None,
        runtime: "js_console_count_reset",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "time",
        class_filter: None,
        runtime: "js_console_time",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeEnd",
        class_filter: None,
        runtime: "js_console_time_end",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeLog",
        class_filter: None,
        runtime: "js_console_time_log",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "groupEnd",
        class_filter: None,
        runtime: "js_console_group_end",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "group",
        class_filter: None,
        runtime: "js_console_group_begin",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "groupCollapsed",
        class_filter: None,
        runtime: "js_console_group_begin",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "profile",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "profileEnd",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "timeStamp",
        class_filter: None,
        runtime: "js_console_noop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "context",
        class_filter: None,
        runtime: "js_console_context",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "console",
        has_receiver: false,
        method: "createTask",
        class_filter: None,
        runtime: "js_console_create_task",
        args: &[NA_F64],
        ret: NR_F64,
    },
];
