//! Feature parity rows for user interaction:
//! Button/TextField/ScrollView state ops, continuous events,
//! and view-driven animations.

use crate::{full, Category::*, Feature, Support::Stub, S, U};

pub(crate) const ROWS: &[Feature] = &[
    // ── Button Ops ───────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_button_set_bordered",
        category: ButtonOps,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_button_set_title",
        category: ButtonOps,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_button_set_font_family",
        category: ButtonOps,
        macos: S,
        ios: Stub,
        android: Stub,
        gtk4: Stub,
        windows: Stub,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_button_set_content_tint_color",
        category: ButtonOps,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_button_set_image_position",
        category: ButtonOps,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── TextField Ops ────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_textfield_focus",
        category: TextFieldOps,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_textfield_set_string",
        category: TextFieldOps,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── ScrollView ───────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_scrollview_set_child",
        category: ScrollView,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_scrollview_scroll_to",
        category: ScrollView,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_scrollview_get_offset",
        category: ScrollView,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    Feature {
        name: "perry_ui_scrollview_set_offset",
        category: ScrollView,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: None,
    },
    // ── Events ───────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_widget_set_on_hover",
        category: Events,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_on_hover"),
    },
    Feature {
        name: "perry_ui_widget_set_on_double_click",
        category: Events,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_set_on_double_click"),
    },
    Feature {
        name: "perry_ui_widget_set_on_click",
        category: Events,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: U,
        web_name: None,
    },
    // Continuous keyboard events (issue #1864). Real impl on every platform.
    full("perry_ui_widget_set_on_key_down", Events),
    full("perry_ui_widget_set_on_key_up", Events),
    full("perry_ui_app_set_on_key_down", Events),
    full("perry_ui_app_set_on_key_up", Events),
    full("perry_ui_focus_widget", Events),
    full("perry_ui_blur_widget", Events),
    full("perry_ui_is_key_down", Events),
    full("perry_ui_current_modifiers", Events),
    // ── Animation ────────────────────────────────────────────────────────
    Feature {
        name: "perry_ui_widget_animate_opacity",
        category: Animation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_animate_opacity"),
    },
    Feature {
        name: "perry_ui_widget_animate_position",
        category: Animation,
        macos: S,
        ios: S,
        android: S,
        gtk4: S,
        windows: S,
        web: S,
        web_name: Some("perry_ui_animate_position"),
    },
];
