use super::*;

pub(super) const ASYNC_HOOKS_ROWS: &[NativeModSig] = &[
    // ========== async_hooks.AsyncLocalStorage ==========
    // `new AsyncLocalStorage()` is dispatched by `lower_builtin_new`; the rows
    // below cover the static and instance methods. `run(store, cb, ...args)` and
    // `exit(cb, ...args)` pass the callback as a full NaN-boxed value (NA_F64)
    // so the runtime can reject a non-callable callback with a `TypeError`
    // (#3092) before mutating the async context, plus a trailing `NA_VARARGS`
    // slot that packs the `...args` into a JS array forwarded to the callback
    // via `js_closure_call_array` (#3093). Pre-fix every method silently
    // no-op'd through the unknown-method sentinel.
    NativeModSig {
        module: "async_hooks",
        has_receiver: false,
        method: "bind",
        class_filter: Some("AsyncLocalStorage"),
        runtime: "js_async_local_storage_static_bind_direct",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: false,
        method: "snapshot",
        class_filter: Some("AsyncLocalStorage"),
        runtime: "js_async_local_storage_static_snapshot_direct",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "run",
        class_filter: None,
        runtime: "js_async_local_storage_run",
        args: &[NA_F64, NA_F64, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: false,
        method: "bind",
        class_filter: Some("AsyncResource"),
        runtime: "js_async_resource_static_bind_direct",
        args: &[NA_F64, NA_F64, NA_F64, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "getStore",
        class_filter: None,
        runtime: "js_async_local_storage_get_store",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "enterWith",
        class_filter: None,
        runtime: "js_async_local_storage_enter_with",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "exit",
        class_filter: None,
        runtime: "js_async_local_storage_exit",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "disable",
        class_filter: None,
        runtime: "js_async_local_storage_disable",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: false,
        method: "createHook",
        class_filter: None,
        runtime: "js_async_hooks_create_hook",
        args: &[NA_F64],
        ret: NR_FOREIGN_PTR,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: false,
        method: "executionAsyncId",
        class_filter: None,
        runtime: "js_async_hooks_execution_async_id",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: false,
        method: "triggerAsyncId",
        class_filter: None,
        runtime: "js_async_hooks_trigger_async_id",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: false,
        method: "executionAsyncResource",
        class_filter: None,
        runtime: "js_async_hooks_execution_async_resource",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "enable",
        class_filter: Some("AsyncHook"),
        runtime: "js_async_hook_enable",
        args: &[],
        ret: NR_FOREIGN_PTR,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "disable",
        class_filter: Some("AsyncHook"),
        runtime: "js_async_hook_disable",
        args: &[],
        ret: NR_FOREIGN_PTR,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "asyncId",
        class_filter: Some("AsyncResource"),
        runtime: "js_async_resource_async_id",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "triggerAsyncId",
        class_filter: Some("AsyncResource"),
        runtime: "js_async_resource_trigger_async_id",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "emitDestroy",
        class_filter: Some("AsyncResource"),
        runtime: "js_async_resource_emit_destroy",
        args: &[],
        ret: NR_FOREIGN_PTR,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "runInAsyncScope",
        class_filter: Some("AsyncResource"),
        runtime: "js_async_resource_run_in_async_scope",
        args: &[NA_F64, NA_F64, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "async_hooks",
        has_receiver: true,
        method: "bind",
        class_filter: Some("AsyncResource"),
        runtime: "js_async_resource_bind",
        args: &[NA_F64, NA_F64],
        ret: NR_NULLABLE_GCPTR,
    },
];
