use super::*;

pub(super) const DATABASES_ROWS: &[NativeModSig] = &[
    // ========== better-sqlite3 ==========
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_sqlite_open",
        args: &[NA_STR],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: true,
        method: "prepare",
        class_filter: None,
        runtime: "js_sqlite_prepare",
        args: &[NA_STR],
        ret: NR_HANDLE_ID,
    },
    // stmt.run/get/all/iterate take JS-side variadic params. The runtime
    // consumes them as a single `*const ArrayHeader`, so VarArgsAsArray
    // packs every user-supplied arg into a real JS array before the call.
    // Pre-#339 these used `NA_F64` and the runtime had to defensively
    // bail when the high-16 bits looked like a NaN-box tag — fine for
    // the no-arg case (TAG_UNDEFINED), but `.all('a')` passed a
    // STRING-tagged f64 that also tripped the bail and the params were
    // silently dropped.
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: true,
        method: "run",
        class_filter: None,
        runtime: "js_sqlite_stmt_run",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: true,
        method: "get",
        class_filter: None,
        runtime: "js_sqlite_stmt_get",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: true,
        method: "all",
        class_filter: None,
        runtime: "js_sqlite_stmt_all",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    // `stmt.raw([toggle])` — flips the statement into raw mode and
    // returns the same handle so `stmt.raw().all(...)` chains. drizzle's
    // PreparedQuery.values() relies on this; without it `stmt.raw` is
    // undefined and the call surfaces as `(number).all is not a
    // function` deeper in the chain. Refs #643. The optional `toggle`
    // arg isn't threaded through the dispatch yet (always enables);
    // extend `args` if a real downstream needs `.raw(false)`.
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: true,
        method: "raw",
        class_filter: None,
        runtime: "js_sqlite_stmt_raw",
        args: &[],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: true,
        method: "exec",
        class_filter: None,
        runtime: "js_sqlite_exec",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "better-sqlite3",
        has_receiver: true,
        method: "close",
        class_filter: None,
        runtime: "js_sqlite_close",
        args: &[],
        ret: NR_VOID,
    },
    // ========== bun:sqlite ==========
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: false,
        method: "Database",
        class_filter: None,
        runtime: "js_bun_sqlite_database_call",
        args: &[NA_F64, NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "query",
        class_filter: Some("Database"),
        runtime: "js_bun_sqlite_database_query",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "prepare",
        class_filter: Some("Database"),
        runtime: "js_bun_sqlite_database_query",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "run",
        class_filter: Some("Database"),
        runtime: "js_bun_sqlite_database_run",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "close",
        class_filter: Some("Database"),
        runtime: "js_node_sqlite_database_sync_close",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "serialize",
        class_filter: Some("Database"),
        runtime: "js_node_sqlite_database_sync_serialize",
        args: &[NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "loadExtension",
        class_filter: Some("Database"),
        runtime: "js_node_sqlite_database_sync_load_extension",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "transaction",
        class_filter: Some("Database"),
        runtime: "js_bun_sqlite_database_transaction",
        args: &[NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "run",
        class_filter: Some("Statement"),
        runtime: "js_node_sqlite_statement_sync_run",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "get",
        class_filter: Some("Statement"),
        runtime: "js_node_sqlite_statement_sync_get",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "all",
        class_filter: Some("Statement"),
        runtime: "js_node_sqlite_statement_sync_all",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "values",
        class_filter: Some("Statement"),
        runtime: "js_bun_sqlite_statement_values",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "safeIntegers",
        class_filter: Some("Statement"),
        runtime: "js_bun_sqlite_statement_safe_integers",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun:sqlite",
        has_receiver: true,
        method: "finalize",
        class_filter: Some("Statement"),
        runtime: "js_bun_sqlite_statement_finalize",
        args: &[],
        ret: NR_VOID,
    },
    // ========== node:sqlite ==========
    NativeModSig {
        module: "sqlite",
        has_receiver: false,
        method: "DatabaseSync",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_call",
        args: &[NA_F64, NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: false,
        method: "Session",
        class_filter: None,
        runtime: "js_node_sqlite_session_call",
        args: &[NA_F64, NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: false,
        method: "StatementSync",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_call",
        args: &[NA_F64, NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: false,
        method: "backup",
        class_filter: None,
        runtime: "js_node_sqlite_backup",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_PROMISE,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "open",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_open",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "close",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_close",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "__perry_dispose__",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_dispose",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "@@__perry_wk_dispose",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_dispose",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "exec",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_exec",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "prepare",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_prepare",
        args: &[NA_F64, NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "serialize",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_serialize",
        args: &[NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "deserialize",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_deserialize",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "function",
        class_filter: Some("DatabaseSync"),
        runtime: "js_node_sqlite_database_sync_function",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "aggregate",
        class_filter: Some("DatabaseSync"),
        runtime: "js_node_sqlite_database_sync_aggregate",
        args: &[NA_F64, NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "enableDefensive",
        class_filter: Some("DatabaseSync"),
        runtime: "js_node_sqlite_database_sync_enable_defensive",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "setAuthorizer",
        class_filter: Some("DatabaseSync"),
        runtime: "js_node_sqlite_database_sync_set_authorizer",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "createTagStore",
        class_filter: Some("DatabaseSync"),
        runtime: "js_node_sqlite_database_sync_create_tag_store",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "createSession",
        class_filter: Some("DatabaseSync"),
        runtime: "js_node_sqlite_database_sync_create_session",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "applyChangeset",
        class_filter: Some("DatabaseSync"),
        runtime: "js_node_sqlite_database_sync_apply_changeset",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "enableLoadExtension",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_enable_load_extension",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "loadExtension",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_load_extension",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "location",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_location",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "isOpen",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_is_open",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "isTransaction",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_is_transaction",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "limits",
        class_filter: None,
        runtime: "js_node_sqlite_database_sync_limits",
        args: &[],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "changeset",
        class_filter: Some("Session"),
        runtime: "js_node_sqlite_session_changeset",
        args: &[],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "patchset",
        class_filter: Some("Session"),
        runtime: "js_node_sqlite_session_patchset",
        args: &[],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "close",
        class_filter: Some("Session"),
        runtime: "js_node_sqlite_session_close",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "__perry_dispose__",
        class_filter: Some("Session"),
        runtime: "js_node_sqlite_session_dispose",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "@@__perry_wk_dispose",
        class_filter: Some("Session"),
        runtime: "js_node_sqlite_session_dispose",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "run",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_run",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "get",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_get",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "all",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_all",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "iterate",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_iterate",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "clear",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_clear",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "size",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_size",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "capacity",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_capacity",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "db",
        class_filter: Some("SQLTagStore"),
        runtime: "js_node_sqlite_sql_tag_store_db",
        args: &[],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "run",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_run",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "get",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_get",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "all",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_all",
        args: &[NA_VARARGS],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "iterate",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_iterate",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "columns",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_columns",
        args: &[],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "setReadBigInts",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_set_read_bigints",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "setReturnArrays",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_set_return_arrays",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "setAllowBareNamedParameters",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_set_allow_bare_named_parameters",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "setAllowUnknownNamedParameters",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_set_allow_unknown_named_parameters",
        args: &[NA_F64],
        ret: NR_I32,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "sourceSQL",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_source_sql",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "sqlite",
        has_receiver: true,
        method: "expandedSQL",
        class_filter: None,
        runtime: "js_node_sqlite_statement_sync_expanded_sql",
        args: &[],
        ret: NR_STR,
    },
];
