use super::*;

pub(super) const NATIVE_PROFILE_ROWS: &[NativeModSig] = &[
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "i8",
        class_filter: None,
        runtime: "js_perry_native_i8",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "i16",
        class_filter: None,
        runtime: "js_perry_native_i16",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "u16",
        class_filter: None,
        runtime: "js_perry_native_u16",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "u8",
        class_filter: None,
        runtime: "js_perry_native_u8",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "i32",
        class_filter: None,
        runtime: "js_perry_native_i32",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "i64",
        class_filter: None,
        runtime: "js_perry_native_i64",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "u32",
        class_filter: None,
        runtime: "js_perry_native_u32",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "u64",
        class_filter: None,
        runtime: "js_perry_native_u64",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "usize",
        class_filter: None,
        runtime: "js_perry_native_usize",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "isize",
        class_filter: None,
        runtime: "js_perry_native_isize",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "f32",
        class_filter: None,
        runtime: "js_perry_native_f32",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "perry/native",
        has_receiver: false,
        method: "f64",
        class_filter: None,
        runtime: "js_perry_native_f64",
        args: &[NA_F64],
        ret: NR_F64,
    },
];
