use super::*;

pub(super) const NODE_MISC_ROWS: &[NativeModSig] = &[
    // ========== node:cluster ==========
    // Primary lifecycle methods mutate runtime state, so ordinary
    // `cluster.setupPrimary(...)` / `.fork(...)` call syntax must route to
    // the same helpers as captured callable exports.
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "setupPrimary",
        class_filter: None,
        runtime: "js_cluster_setup_primary",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "setupMaster",
        class_filter: None,
        runtime: "js_cluster_setup_primary",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "fork",
        class_filter: None,
        runtime: "js_cluster_fork",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "disconnect",
        class_filter: None,
        runtime: "js_cluster_disconnect",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "on",
        class_filter: None,
        runtime: "js_cluster_on",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "addListener",
        class_filter: None,
        runtime: "js_cluster_on",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "once",
        class_filter: None,
        runtime: "js_cluster_once",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "prependListener",
        class_filter: None,
        runtime: "js_cluster_prepend_listener",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "prependOnceListener",
        class_filter: None,
        runtime: "js_cluster_prepend_once_listener",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "emit",
        class_filter: None,
        runtime: "js_cluster_emit",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "eventNames",
        class_filter: None,
        runtime: "js_cluster_event_names",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "listenerCount",
        class_filter: None,
        runtime: "js_cluster_listener_count",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "listeners",
        class_filter: None,
        runtime: "js_cluster_listeners",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "rawListeners",
        class_filter: None,
        runtime: "js_cluster_raw_listeners",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "setMaxListeners",
        class_filter: None,
        runtime: "js_cluster_set_max_listeners",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "getMaxListeners",
        class_filter: None,
        runtime: "js_cluster_get_max_listeners",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "removeListener",
        class_filter: None,
        runtime: "js_cluster_remove_listener",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "off",
        class_filter: None,
        runtime: "js_cluster_remove_listener",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cluster",
        has_receiver: false,
        method: "removeAllListeners",
        class_filter: None,
        runtime: "js_cluster_remove_all_listeners_args",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    // ========== node:vm ==========
    NativeModSig {
        module: "vm",
        has_receiver: false,
        method: "createContext",
        class_filter: None,
        runtime: "js_vm_create_context",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // ========== node:repl ==========
    NativeModSig {
        module: "repl",
        has_receiver: false,
        method: "start",
        class_filter: None,
        runtime: "js_repl_start",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "repl",
        has_receiver: false,
        method: "REPLServer",
        class_filter: None,
        runtime: "js_repl_repl_server_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "repl",
        has_receiver: false,
        method: "Recoverable",
        class_filter: None,
        runtime: "js_repl_recoverable_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // ========== node:querystring ==========
    // Module-level functions. `decode` / `encode` route to the same
    // runtime symbols as `parse` / `stringify` so the test's
    // `decode === parse` identity-equality check passes.
    NativeModSig {
        module: "querystring",
        has_receiver: false,
        method: "escape",
        class_filter: None,
        runtime: "js_querystring_escape",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "querystring",
        has_receiver: false,
        method: "unescape",
        class_filter: None,
        runtime: "js_querystring_unescape",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "querystring",
        has_receiver: false,
        method: "unescapeBuffer",
        class_filter: None,
        runtime: "js_querystring_unescape_buffer",
        args: &[NA_F64, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "querystring",
        has_receiver: false,
        method: "parse",
        class_filter: None,
        runtime: "js_querystring_parse",
        args: &[NA_F64, NA_F64, NA_F64, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "querystring",
        has_receiver: false,
        method: "decode",
        class_filter: None,
        runtime: "js_querystring_parse",
        args: &[NA_F64, NA_F64, NA_F64, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "querystring",
        has_receiver: false,
        method: "stringify",
        class_filter: None,
        runtime: "js_querystring_stringify",
        args: &[NA_F64, NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "querystring",
        has_receiver: false,
        method: "encode",
        class_filter: None,
        runtime: "js_querystring_stringify",
        args: &[NA_F64, NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
];
