use super::*;

/// node:dns + node:dns/promises shape-stub rows (#793). Split out of
/// node_core.rs to keep that file under the 2000-line CI gate.
pub(super) const NODE_DNS_ROWS: &[NativeModSig] = &[
    // ========== Node dns shape stubs ==========
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "lookup",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "lookupService",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolve",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolve4",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolve6",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveAny",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveCaa",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveCname",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveMx",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveNaptr",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveNs",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolvePtr",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveSoa",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveSrv",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveTlsa",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "resolveTxt",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "reverse",
        class_filter: None,
        runtime: "js_dns_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "getServers",
        class_filter: None,
        runtime: "js_dns_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "setServers",
        class_filter: None,
        runtime: "js_dns_set_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "setDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_set_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "getDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_get_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: false,
        method: "Resolver",
        class_filter: None,
        runtime: "js_dns_resolver_new",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "cancel",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "getServers",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "setServers",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns",
        has_receiver: true,
        method: "setLocalAddress",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "lookup",
        class_filter: None,
        runtime: "js_dns_promises_lookup",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "lookupService",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolve",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolve4",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolve6",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveAny",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveCaa",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveCname",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveMx",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveNaptr",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveNs",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolvePtr",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveSoa",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveSrv",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveTlsa",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "resolveTxt",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "reverse",
        class_filter: None,
        runtime: "js_dns_promises_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "getServers",
        class_filter: None,
        runtime: "js_dns_promises_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "setServers",
        class_filter: None,
        runtime: "js_dns_promises_set_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "setDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_set_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "getDefaultResultOrder",
        class_filter: None,
        runtime: "js_dns_get_default_result_order",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: false,
        method: "Resolver",
        class_filter: None,
        runtime: "js_dns_promises_resolver_new",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: true,
        method: "cancel",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_noop",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "dns/promises",
        has_receiver: true,
        method: "getServers",
        class_filter: Some("Resolver"),
        runtime: "js_dns_resolver_get_servers",
        args: &[NA_VARARGS],
        ret: NR_F64,
    },
];
