#!/usr/bin/env python3
"""Snapshot ratchet for the gap suite.

`run_gap_tests.sh` used to gate with `comm -23 <failures> <known_failures.json>`
— "fail CI on any failure not already triaged". That is one-directional: it
catches regressions but is blind to a listed test that starts PASSING, so a
fixed test keeps its skip-list entry forever and the file rots into a set of
orphans nobody can revalidate (#797).

This replaces it with a GENERATED snapshot of every non-passing test, checked
both ways:

  * not in snapshot, now failing   regression. Fix it, or accept it.
  * in snapshot, now passing       improvement. Must be recorded, so an entry
                                   can never silently outlive the bug it tracks.
  * in snapshot, different status  e.g. parity_fail -> crash, or the oracle
                                   stopped covering it (node_fail). Recorded
                                   explicitly rather than dropped from the
                                   denominator, because that hole is exactly
                                   how a Node 22 pin hid 14 tests for months
                                   (#6364).

Accept the current state with:

    UPDATE_SNAPSHOT=1 ./scripts/run_gap_tests.sh

Passing tests are deliberately NOT stored: "fails and is not listed" already
means regression, so listing them would quadruple the file without adding a
single detection. The snapshot stays small enough to review in a PR diff.

Statuses only, never program output: the harness's truncation marker embeds an
exact line count (`TRUNCATED ... (total: N)`) that is not stable across runs
for a flapping test (#796).

Sharding: CI runs `--shard N/8`, so a report covers a slice of the suite. Both
modes therefore act only on tests PRESENT in the report — a shard neither
checks nor rewrites its siblings' entries. Update prunes an entry only when
its test file is gone from disk, which is decidable from any shard.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REPORT = ROOT / "test-parity/reports/latest.json"
DEFAULT_SNAPSHOT = ROOT / "test-parity/gap_snapshot.json"
TEST_DIR = ROOT / "test-files"

PASS = "pass"
ALL_STATUSES = frozenset(
    {PASS, "parity_fail", "compile_fail", "crash", "node_fail", "skipped"}
)
TRIAGE_FIELDS = ("issue", "added", "category", "reason")

SCHEMA_DOC = {
    "description": (
        "Generated by scripts/gap_snapshot.py — do not hand-edit statuses. "
        "Lists every gap test that is NOT passing; a test absent from `tests` "
        "is expected to pass. CI fails on any divergence in EITHER direction "
        "(new failure, or a listed test that now passes). Regenerate with "
        "UPDATE_SNAPSHOT=1 ./scripts/run_gap_tests.sh and commit the diff."
    ),
    "fields": {
        "status": "parity_fail | compile_fail | crash | node_fail | skipped",
        "issue": "GitHub issue tracking this failure, or null when untriaged.",
        "added": "ISO date (YYYY-MM-DD) the test first entered the snapshot.",
        "category": (
            "ci-env | module-inventory | bug-open | bug-stale | gap-categorical | "
            "gap-bisect | untriaged — see test-parity/README.md."
        ),
        "reason": "Free text; most-actionable signal first.",
    },
}


def load_report(path: Path) -> dict[str, str]:
    """Test id -> status, from the harness's `results[]`.

    `results[]` (not `failures{}`) is the source: it carries node_fail and
    skipped too, which is what makes an oracle-coverage change visible.
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    results = data.get("results") or []
    out: dict[str, str] = {}
    for entry in results:
        test_id, status = entry.get("id"), entry.get("status")
        if not test_id or status not in ALL_STATUSES:
            raise ValueError(f"malformed report entry: {entry!r}")
        out[test_id] = status
    if not out:
        raise ValueError(f"report {path} has no results[] — did the harness run?")
    return out


def load_snapshot(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8")).get("tests", {})


def write_snapshot(path: Path, tests: dict[str, dict]) -> None:
    payload = {"_schema": SCHEMA_DOC, "tests": dict(sorted(tests.items()))}
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def diff(report: dict[str, str], tests: dict[str, dict]) -> list[tuple[str, str, str, str]]:
    """(kind, test_id, expected, actual) for every divergence in this slice."""
    out = []
    for test_id, actual in sorted(report.items()):
        expected = tests.get(test_id, {}).get("status", PASS)
        if expected == actual:
            continue
        if expected == PASS:
            kind = "regression"
        elif actual == PASS:
            kind = "improvement"
        else:
            kind = "changed"
        out.append((kind, test_id, expected, actual))
    return out


def test_file_exists(test_id: str) -> bool:
    return (TEST_DIR / f"{test_id}.ts").exists()


def merge(
    report: dict[str, str],
    tests: dict[str, dict],
    today: str,
    exists=test_file_exists,
) -> dict[str, dict]:
    """Fold this run's statuses in, preserving triage metadata."""
    merged = dict(tests)
    for test_id, status in report.items():
        if status == PASS:
            # Fixed — drop the entry so it can't outlive the bug it tracked.
            merged.pop(test_id, None)
            continue
        previous = merged.get(test_id, {})
        entry: dict[str, object] = {"status": status}
        if previous:
            # Carry triage across a status change: parity_fail -> crash is
            # still the same open bug.
            entry.update({f: previous[f] for f in TRIAGE_FIELDS if f in previous})
        else:
            entry.update(
                {"issue": None, "added": today, "category": "untriaged", "reason": ""}
            )
        merged[test_id] = entry
    # A test file that no longer exists cannot be run by any shard, so pruning
    # it is safe even from a partial report.
    return {test_id: entry for test_id, entry in merged.items() if exists(test_id)}


def report_diffs(
    diffs: list[tuple[str, str, str, str]], snapshot_path: Path = DEFAULT_SNAPSHOT
) -> None:
    order = {"regression": 0, "changed": 1, "improvement": 2}
    headers = {
        "regression": "REGRESSIONS — these were expected to pass:",
        "changed": "STATUS CHANGES — including tests the oracle stopped covering:",
        "improvement": (
            "IMPROVEMENTS — these now pass; record them so the entry can't go stale:"
        ),
    }
    for kind in sorted({d[0] for d in diffs}, key=lambda k: order[k]):
        print(f"\n{headers[kind]}", file=sys.stderr)
        for _, test_id, expected, actual in [d for d in diffs if d[0] == kind]:
            print(f"  - {test_id}: {expected} -> {actual}", file=sys.stderr)
    print(
        "\nFix the regressions, then accept the rest with:\n"
        "  UPDATE_SNAPSHOT=1 ./scripts/run_gap_tests.sh\n"
        f"and commit {snapshot_path}.",
        file=sys.stderr,
    )


def self_test() -> int:
    snapshot = {
        "test_gap_b": {
            "status": "parity_fail",
            "issue": "42",
            "added": "2026-01-01",
            "category": "bug-open",
            "reason": "why",
        },
        "test_gap_skip": {"status": "skipped", "issue": None, "added": "2026-01-01",
                          "category": "ci-env", "reason": ""},
    }
    live = lambda _test_id: True  # noqa: E731 — every fixture test "exists"

    # Both directions, from a snapshot that stores only non-passing tests.
    kinds = {
        d[1]: d[0]
        for d in diff({"test_gap_a": "crash", "test_gap_b": "pass"}, snapshot)
    }
    assert kinds == {"test_gap_a": "regression", "test_gap_b": "improvement"}, kinds
    # An unlisted test that passes is the expected case — never a diff.
    assert diff({"test_gap_a": "pass"}, snapshot) == []
    # A listed test still failing the same way is not a diff either.
    assert diff({"test_gap_b": "parity_fail"}, snapshot) == []
    # An oracle-coverage loss is a diff, not a silent drop.
    assert diff({"test_gap_a": "node_fail"}, snapshot)[0][0] == "regression"
    assert diff({"test_gap_b": "crash"}, snapshot)[0][0] == "changed"

    # Triage survives a status change; a fixed test drops out entirely.
    merged = merge(
        {"test_gap_b": "crash", "test_gap_c": "parity_fail"}, snapshot, "2026-07-22", live
    )
    assert merged["test_gap_b"]["issue"] == "42", merged["test_gap_b"]
    assert merged["test_gap_c"]["category"] == "untriaged", merged["test_gap_c"]
    merged = merge({"test_gap_b": "pass"}, snapshot, "2026-07-22", live)
    assert "test_gap_b" not in merged, merged
    # Entries this shard did not run survive its update.
    assert merged["test_gap_skip"]["status"] == "skipped"

    # Pruning keys off the test file, so it is decidable from one shard.
    assert merge({}, snapshot, "2026-07-22", lambda _t: False) == {}
    assert merge({}, snapshot, "2026-07-22", live) == snapshot

    print("gap_snapshot self-test OK")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", nargs="?", choices=("check", "update"), default="check")
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--snapshot", type=Path, default=DEFAULT_SNAPSHOT)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    try:
        report = load_report(args.report)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"gap snapshot error: {exc}", file=sys.stderr)
        return 2
    tests = load_snapshot(args.snapshot)

    if args.mode == "update":
        merged = merge(report, tests, date.today().isoformat())
        write_snapshot(args.snapshot, merged)
        print(
            f"Snapshot updated from {len(report)} run tests: "
            f"{len(merged)} non-passing entries -> {args.snapshot}"
        )
        return 0

    diffs = diff(report, tests)
    if diffs:
        report_diffs(diffs, args.snapshot)
        return 1
    print(
        f"Gap snapshot OK — {len(report)} tests match {args.snapshot} "
        f"({len(tests)} known non-passing)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
